Repository TykTechnologies/tyk, pull requests merged in 2022-12, with the labels that each got.

#4461 [TT-1952] Add latency analytics to cache hit
  gateway/mw_redis_cache.go
Labels: release-4, release-4.3, release-4-lts

#4460 [TT-5987] Mark test as flaky to skip in CI
  gateway/gateway_test.go
Labels: release-4, release-4.3

#4459 [TT-7222] Move golangci-lint config from GH action to file
  .github/workflows/ci-tests.yml
  .golangci.yml
Labels: release-4, release-4.3

#4563 [CI] Sync automation: Syncing commits from master
  .github/dependabot.yml
  .github/workflows/api-tests.yml
  .github/workflows/release.yml
  ci/Dockerfile.slim
  ci/Dockerfile.std
  ci/aws/byol.pkr.hcl
  ci/aws/hybrid/tyk_hybrid.conf
  ci/goreleaser/goreleaser-el7.yml
  ci/goreleaser/goreleaser.yml
  ci/images/hybrid/tyk/tyk.conf
  ci/images/hybrid/tyk/tyk.conf.example
  ci/images/plugin-compiler/Dockerfile
  ci/install/before_install.sh
  ci/install/data/tyk.standalone.conf
  ci/install/post_install.sh
  ci/install/post_remove.sh
  ci/install/post_trans.sh
  ci/terraform/outputs.tf
  ci/tests/plugin-compiler/testplugin/go.mod
  ci/tests/plugin-compiler/testplugin/go.sum
  ci/tests/python-plugins/src/tyk.conf
Labels: sync-automation

#4567 [CI] Sync automation: Syncing commits from master
  .github/dependabot.yml
  .github/workflows/api-tests.yml
  .github/workflows/release.yml
  ci/Dockerfile.slim
  ci/Dockerfile.std
  ci/aws/byol.pkr.hcl
  ci/aws/hybrid/tyk_hybrid.conf
  ci/goreleaser/goreleaser-el7.yml
  ci/goreleaser/goreleaser.yml
  ci/images/hybrid/tyk/tyk.conf
  ci/images/hybrid/tyk/tyk.conf.example
  ci/install/before_install.sh
  ci/install/data/tyk.standalone.conf
  ci/install/post_install.sh
  ci/install/post_remove.sh
  ci/install/post_trans.sh
  ci/terraform/outputs.tf
  ci/tests/python-plugins/src/tyk.conf
Labels: sync-automation

#4568 [CI] Sync automation: Syncing commits from master
  .github/dependabot.yml
  .github/workflows/api-tests.yml
  .github/workflows/release.yml
  ci/Dockerfile.slim
  ci/Dockerfile.std
  ci/aws/byol.pkr.hcl
  ci/goreleaser/goreleaser-el7.yml
  ci/goreleaser/goreleaser.yml
  ci/install/before_install.sh
  ci/install/post_install.sh
  ci/install/post_remove.sh
  ci/install/post_trans.sh
  ci/terraform/outputs.tf
Labels: sync-automation

#4603 [CI] Sync automation: Syncing commits from master
  .github/dependabot.yml
  .github/workflows/api-tests.yml
  .github/workflows/release.yml
  ci/Dockerfile.std
  ci/aws/byol.pkr.hcl
  ci/goreleaser/goreleaser-el7.yml
  ci/goreleaser/goreleaser.yml
  ci/install/before_install.sh
  ci/install/post_install.sh
  ci/install/post_remove.sh
  ci/install/post_trans.sh
  ci/terraform/outputs.tf
Labels: sync-automation

#4602 [CI] Sync automation: Syncing commits from master
  .github/workflows/api-tests.yml
  .github/workflows/release.yml
Labels: sync-automation
