Repository TykTechnologies/tyk, pull requests merged in 2023-08, with the labels that each got.

#5424 [TD-2163] triggere release 5.2 branches creation
  repo-policy/main.tf
Labels: Task, Tyk DevOps

#5426 [TT-9829] Fix checking json.Marshal errors in tests
  gateway/api_test.go
  gateway/gateway_test.go
  gateway/grpc_streaming_client_test.go
  gateway/oauth_manager_test.go
  gateway/testutil.go
  test/json.go
  test/json_test.go
Labels: Tyk Product Development, Task

#5429 [TT-8710]: Better error message for invalid variables (update go tools)
  go.mod
  go.sum
Labels: Tyk Product Development, Story

#5430 [TT-9748] Update swagger.yml
  swagger.yml
Labels: Tyk Product Development, Task

#5432 Merging to release-5.2: [TT-9829] Fix checking json.Marshal errors in tests (#5426)
  gateway/api_test.go
  gateway/gateway_test.go
  gateway/grpc_streaming_client_test.go
  gateway/oauth_manager_test.go
  gateway/testutil.go
  test/json.go
  test/json_test.go
Labels: Tyk Product Development, Task

#5437 Merging to release-5-lts: [TT-9800] added jira lint that runs for every PR agains master (#5422)
  .github/workflows/jira-lint.yml
Labels: Tyk Product Development, Task

#5438 fix subscriptions headers not being passed upstream (TT-9670)
  apidef/adapter/gqlengineadapter/adapter_proxy_only.go
  gateway/mw_graphql_test.go
  gateway/mw_graphql_transport.go
  gateway/mw_graphql_transport_test.go
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
  gateway/testutil.go
  go.mod
  go.sum
Labels: bug, Tyk Product Development

#5439 subscription headers not being passed upstream (TT-9670)
  apidef/adapter/graphql_config_adapter.go
  gateway/mw_graphql_test.go
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
  gateway/testutil.go
  go.mod
  go.sum
Labels: bug, Tyk Product Development

#5419 [TT-9628] Reset fields inside classic API def but removed from OAS
  apidef/oas/authentication.go
  apidef/oas/middleware.go
  apidef/oas/oas.go
  apidef/oas/oas_test.go
  apidef/oas/operation.go
  apidef/oas/root.go
  apidef/oas/root_test.go
  apidef/oas/security.go
  apidef/oas/security_test.go
  apidef/oas/server.go
  apidef/oas/upstream.go
Labels: Tyk Product Development, Story

#5445 Merging to release-5.2: [TT-9628] Reset fields inside classic API def but removed from OAS (#5419)
  apidef/oas/authentication.go
  apidef/oas/middleware.go
  apidef/oas/oas.go
  apidef/oas/oas_test.go
  apidef/oas/operation.go
  apidef/oas/root.go
  apidef/oas/root_test.go
  apidef/oas/security.go
  apidef/oas/security_test.go
  apidef/oas/server.go
  apidef/oas/upstream.go
Labels: Tyk Product Development, Story

#5446 Merging to release-5-lts: [TT-9628] Reset fields inside classic API def but removed from OAS (#5419)
  apidef/oas/authentication.go
  apidef/oas/middleware.go
  apidef/oas/oas.go
  apidef/oas/oas_test.go
  apidef/oas/operation.go
  apidef/oas/root.go
  apidef/oas/root_test.go
  apidef/oas/security.go
  apidef/oas/security_test.go
  apidef/oas/server.go
  apidef/oas/upstream.go
Labels: Tyk Product Development, Story

#5447 [TT-9628/TT-9724] Fix extractTo of custom plugin
  apidef/api_definitions.go
  apidef/oas/authentication.go
  apidef/oas/oas_test.go
  apidef/oas/security.go
Labels: Tyk Product Development, Sub-task

#5451 Merging to release-5-lts: [TT-9628/TT-9724] Fix extractTo of custom plugin (#5447)
  apidef/api_definitions.go
  apidef/oas/authentication.go
  apidef/oas/oas_test.go
  apidef/oas/security.go
Labels: Tyk Product Development, Sub-task

#5452 Merging to release-5.2: [TT-9628/TT-9724] Fix extractTo of custom plugin (#5447)
  apidef/api_definitions.go
  apidef/oas/authentication.go
  apidef/oas/oas_test.go
  apidef/oas/security.go
Labels: Tyk Product Development, Sub-task

#5442 TT-9849 rename otel config to be exported as opentelemetry
  config/config.go
  gateway/server_test.go
  internal/graphql/otel_graphql_engine_test.go
  internal/otel/otel.go
  internal/otel/otel_test.go
Labels: Tyk Product Development, Story

#5370 [TT-9493] Detect breaking changes with github action
  .github/workflows/api-changes.yml
  .taskfiles/godoc/Taskfile.yml
  internal/maps/flatten.go
  log/log.go
Labels: Tyk Product Development, Story

#5458 Merging to release-5-lts: [TT-9493] Detect breaking changes with github action (#5370)
  .github/workflows/api-changes.yml
  .taskfiles/godoc/Taskfile.yml
  internal/maps/flatten.go
  log/log.go
Labels: Tyk Product Development, Story

#5459 Merging to release-5.2: [TT-9493] Detect breaking changes with github action (#5370)
  .github/workflows/api-changes.yml
  .taskfiles/godoc/Taskfile.yml
  internal/maps/flatten.go
  log/log.go
Labels: Tyk Product Development, Story

#5457 [TT-9227] Persist GraphQL doesn't work in conjunction with Response Body Transform
  gateway/mw_persist_graphql_operation.go
  gateway/mw_persist_graphql_operation_test.go
Labels: bug, Tyk Product Development

#5461 Merging to release-5.2: [TT-9227] Persist GraphQL doesn't work in conjunction with Response Body Transform (#5457)
  gateway/mw_persist_graphql_operation.go
  gateway/mw_persist_graphql_operation_test.go
Labels: bug, Tyk Product Development

#5455 TT-9849 apply config docs suggestions of opentelemetry config options
  config/config.go
Labels: Tyk Product Development, Story

#5231 [TT-9284] Ensure that old transport will close idle connections
  gateway/proxy_muxer.go
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
  gateway/server.go
  gateway/testutil.go
  internal/httputil/connection_watcher.go
  internal/httputil/connection_watcher_test.go
Labels: bug, Tyk Product Development
