Repository TykTechnologies/tyk, pull requests merged in 2024-09, with the labels that each got.

#6452 [TT-12562] go 1.22 upgrade
  .github/workflows/api-changes.yml
  .github/workflows/ci-tests.yml
  .github/workflows/plugin-compiler-build.yml
  .github/workflows/release.yml
  .go-version
  .golangci.yml
  Dockerfile
  README.md
  Taskfile.yml
  ci/images/plugin-compiler/Dockerfile
  ci/images/plugin-compiler/Taskfile.yml
  ci/smoke-tests/plugin-aliasing/foobar-plugin/go.mod
  ci/smoke-tests/plugin-aliasing/helloworld-plugin/go.mod
  ci/tests/plugin-compiler/README.md
  ci/tests/plugin-compiler/Taskfile.yml
  ci/tests/plugin-compiler/testdata/basic-plugin/go.mod
  ci/tests/plugin-compiler/testdata/test-plugin/go.mod
  gateway/cert_go1.10_test.go
  go.mod
Labels: enhancement, Tests, Review effort [1-5]: 3, configuration changes

#6476 [TT-12815] Upgraded the release-5.3 branch to golang 1.22
  .github/workflows/api-changes.yml
  .github/workflows/ci-tests.yml
  .github/workflows/plugin-compiler-build.yml
  .github/workflows/release.yml
  .go-version
  .golangci.yml
  Dockerfile
  Taskfile.yml
  ci/Dockerfile.distroless
  ci/Dockerfile.std
  ci/images/hybrid/Dockerfile
  ci/images/plugin-compiler/Dockerfile
  ci/images/plugin-compiler/Taskfile.yml
  ci/smoke-tests/plugin-aliasing/foobar-plugin/go.mod
  ci/smoke-tests/plugin-aliasing/helloworld-plugin/go.mod
  ci/tests/plugin-compiler/README.md
  ci/tests/plugin-compiler/Taskfile.yml
  ci/tests/plugin-compiler/testdata/basic-plugin/go.mod
  ci/tests/plugin-compiler/testdata/test-plugin/go.mod
  coprocess/bindings/python/coprocess_object_pb2.py
  coprocess/bindings/python/coprocess_object_pb2_grpc.py
  gateway/cert_go1.10_test.go
  go.mod
Labels: enhancement, Review effort [1-5]: 3, configuration changes

#6479 Merging to release-5.3: [TT-11726]: This optimizes the deletion of keys using a single command (#6427)
  gateway/api_test.go
  gateway/auth_manager.go
  gateway/auth_manager_test.go
  gateway/ldap_auth_handler.go
  gateway/rpc_storage_handler.go
  storage/dummy.go
  storage/mdcb_storage.go
  storage/redis_cluster.go
  storage/redis_cluster_test.go
  storage/storage.go
Labels: enhancement, Tests, Review effort [1-5]: 3

#6481 [TT-12975] Fix flaky test caused by missed Close invocation
  .taskfiles/test.yml
  gateway/server_test.go
Labels: Review effort [1-5]: 1, Tests, Bug fix

#6344 [TT-12355] added log format config, func and test cases
  cli/linter/schema.json
  config/config.go
  gateway/server.go
  gateway/testutil.go
  go.mod
  go.sum
  log/Taskfile.yml
  log/json_formatter.go
  log/log.go
  log/log_test.go
  log/translation_formatter.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#6484 Merging to release-5.3: [TT-12355] added log format config, func and test cases (#6344)
  cli/linter/schema.json
  config/config.go
  gateway/server.go
  gateway/testutil.go
  go.mod
  go.sum
  log/Taskfile.yml
  log/json_formatter.go
  log/log.go
  log/log_test.go
  log/translation_formatter.go
Labels: enhancement, Tests, Review effort [1-5]: 3

#6480 [TT-1944] Fix regex matching for parameters
  .taskfiles/test.yml
  gateway/api_definition.go
  gateway/api_definition_test.go
Labels: Tests, Review effort [1-5]: 2, Bug fix

#6485 Revert "Merging to release-5.3: [TT-12355] added log format config, func and test cases (#6344)"
  cli/linter/schema.json
  config/config.go
  gateway/server.go
  gateway/testutil.go
  go.mod
  go.sum
  log/Taskfile.yml
  log/json_formatter.go
  log/log.go
  log/log_test.go
  log/translation_formatter.go
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#6486 Merging to release-5.3: [TT-1944] Fix regex matching for parameters (#6480)
  .taskfiles/test.yml
  gateway/api_definition.go
  gateway/api_definition_test.go
Labels: Tests, Review effort [1-5]: 2, Bug fix

#6487 added a waitgroup to wait until all the pool connections are dialed
  rpc/rpc_client.go
Labels: enhancement, Review effort [1-5]: 2

#6491 [TT-12964] ignore endpoint rate limit configurations when rate limit partition is disabled
  gateway/policy_test.go
  gateway/testdata/policies.json
  internal/policy/apply.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#6494 [TT-13011] implement combining endpoint rate limits from non partitioned policies.
  .github/workflows/ci-tests.yml
  gateway/policy_test.go
  gateway/testdata/policies.json
  internal/policy/apply.go
  internal/policy/apply_test.go
  internal/policy/testdata/apply_endpoint_rl.json
Labels: enhancement, Tests, Review effort [1-5]: 4

#6492 [TT-13041] Adjust quota handling of missing or expired keys
  .github/workflows/ci-tests.yml
  gateway/api_test.go
  gateway/gateway_test.go
  gateway/middleware_test.go
  gateway/mw_external_oauth_test.go
  gateway/mw_rate_limiting_test.go
  gateway/rpc_storage_handler_test.go
  gateway/server.go
  gateway/session_manager.go
  test/util.go
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#6499 [TT-13041] [release-5.3] backport
  .github/workflows/ci-tests.yml
  gateway/api_test.go
  gateway/gateway_test.go
  gateway/middleware_test.go
  gateway/mw_external_oauth_test.go
  gateway/mw_rate_limiting_test.go
  gateway/rpc_storage_handler_test.go
  gateway/server.go
  gateway/session_manager.go
  gateway/testutil.go
  test/util.go
Labels: enhancement, Tests, Bug fix, Review effort [1-5]: 3

#6504 [TT-13048] Flaky test due to using httpbin org, improvements
  docker/services/httpbin.yml
  tests/regression/issue_10104_test.go
  tests/regression/issue_11585_test.go
  tests/regression/issue_11806_test.go
  tests/regression/regression_test.go
  tests/regression/testdata/issue-11806-api-with-domain.json
Labels: enhancement, Tests, Review effort [1-5]: 2

#6505 Merging to release-5.3: [TT-13048] Flaky test due to using httpbin org, improvements (#6504)
  docker/services/httpbin.yml
  tests/regression/issue_10104_test.go
  tests/regression/issue_11585_test.go
  tests/regression/issue_11806_test.go
  tests/regression/regression_test.go
  tests/regression/testdata/issue-11806-api-with-domain.json
Labels: Tests, Review effort [1-5]: 2

#6475 [TT-12865] URL matching prefixes/explicit, regex support
  cli/linter/schema.json
  config/config.go
  gateway/api_definition.go
  gateway/api_definition_test.go
  gateway/model_apispec.go
  gateway/model_urlspec.go
  gateway/mw_granular_access.go
  gateway/mw_granular_access_test.go
  gateway/session_manager.go
  gateway/session_manager_test.go
  internal/httputil/mux.go
  internal/httputil/mux_test.go
  tests/regression/issue_12865_test.go
  tests/regression/testdata/issue-12865.json
  user/session.go
  user/session_test.go
Labels: Tests, Bug fix, Review effort [1-5]: 3

#6506 [TT-12865] Rename config parameter, update usage, support mux params on legacy
  .taskfiles/test.yml
  cli/linter/schema.json
  config/config.go
  gateway/api_definition.go
  gateway/api_definition_test.go
  gateway/mw_granular_access.go
  gateway/mw_granular_access_test.go
  gateway/session_manager.go
  tests/regression/issue_12865_test.go
Labels: enhancement, Review effort [1-5]: 2

#6496 [TT-12893]: Adding first implementation of streams API
  .gitignore
  apidef/oas/linter_test.go
  benthos.yaml
  cli/linter/schema.json
  config/config.go
  gateway/api_definition.go
  gateway/api_loader.go
  gateway/middleware.go
  gateway/mw_context_vars.go
  gateway/mw_streaming.go
  gateway/mw_streaming_test.go
  gateway/testutil.go
  go.mod
  go.sum
  internal/graphql/graphql_request.go
  internal/graphql/graphql_request_test.go
  internal/portal/portal_client.go
  internal/portal/portal_output.go
  internal/portal/portal_output_test.go
  internal/portal/portal_test.go
  internal/streaming/manager.go
  internal/streaming/manager_test.go
Labels: enhancement, Tests, Review effort [1-5]: 5

#6509 Revert "[TT-12893]: Adding first implementation of streams API"
  .gitignore
  apidef/oas/linter_test.go
  benthos.yaml
  cli/linter/schema.json
  config/config.go
  gateway/api_definition.go
  gateway/api_loader.go
  gateway/middleware.go
  gateway/mw_context_vars.go
  gateway/mw_streaming.go
  gateway/mw_streaming_test.go
  gateway/testutil.go
  go.mod
  go.sum
  internal/graphql/graphql_request.go
  internal/graphql/graphql_request_test.go
  internal/portal/portal_client.go
  internal/portal/portal_output.go
  internal/portal/portal_output_test.go
  internal/portal/portal_test.go
  internal/streaming/manager.go
  internal/streaming/manager_test.go
Labels: enhancement, dependencies, Bug fix, Review effort [1-5]: 3

#6508 [TT-12494] Fix flaky TestCacheEtag and related cache tests
  .github/workflows/ci-tests.yml
  .taskfiles/test.yml
  docker/services/Taskfile.yml
  gateway/gateway_test.go
  tests/regression/Taskfile.yml
  tests/regression/issue_10104_test.go
  tests/regression/issue_11806_test.go
  tests/regression/issue_12865_test.go
  tests/regression/regression_test.go
  tests/regression/testdata/issue-12865.json
Labels: enhancement, Tests, Review effort [1-5]: 2

#6507 Merging to release-5.3: [TT-12865] Rename config parameter, update usage, support mux params on legacy (#6506)
  .github/workflows/ci-tests.yml
  Taskfile.yml
  cli/linter/schema.json
  config/config.go
  docker/services/Taskfile.yml
  gateway/api_definition.go
  gateway/api_definition_test.go
  gateway/gateway_test.go
  gateway/model_apispec.go
  gateway/model_urlspec.go
  gateway/mw_granular_access.go
  gateway/mw_granular_access_test.go
  internal/httputil/mux.go
  internal/httputil/mux_test.go
  tests/regression/Taskfile.yml
  tests/regression/issue_10104_test.go
  tests/regression/issue_11806_test.go
  tests/regression/issue_12865_test.go
  tests/regression/regression_test.go
  tests/regression/testdata/issue-12865.json
Labels: enhancement, Tests, Review effort [1-5]: 4

#6510 [TT-12865] [5.3.5 backport] Rename config parameter, update usage, support mux params on legacy
  .github/workflows/ci-tests.yml
  .taskfiles/test.yml
  Taskfile.yml
  cli/linter/schema.json
  config/config.go
  docker/services/Taskfile.yml
  docker/services/httpbin.yml
  gateway/api_definition.go
  gateway/api_definition_test.go
  gateway/gateway_test.go
  gateway/handler_error.go
  gateway/model_apispec.go
  gateway/model_urlspec.go
  gateway/mw_granular_access.go
  gateway/mw_granular_access_test.go
  gateway/mw_request_signing.go
  internal/httputil/Taskfile.yml
  internal/httputil/connection_watcher.go
  internal/httputil/mux.go
  internal/httputil/mux_test.go
  internal/httputil/response.go
  internal/httputil/streaming_test.go
  internal/maps/strings.go
  test/util.go
  tests/regression/Taskfile.yml
  tests/regression/issue_10104_test.go
  tests/regression/issue_11806_test.go
  tests/regression/issue_12865_test.go
  tests/regression/regression_test.go
  tests/regression/testdata/issue-12865.json
Labels: enhancement, Tests, Review effort [1-5]: 3

#6513 [TT-1944/TT-12550/TT-12865] Backport critical fixes
  .taskfiles/test.yml
  cli/linter/schema.json
  config/config.go
  gateway/api_definition.go
  gateway/api_definition_test.go
  gateway/handler_error.go
  gateway/model_apispec.go
  gateway/model_urlspec.go
  gateway/mw_granular_access.go
  gateway/mw_granular_access_test.go
  gateway/mw_request_signing.go
  internal/httputil/Taskfile.yml
  internal/httputil/connection_watcher.go
  internal/httputil/mux.go
  internal/httputil/mux_test.go
  internal/httputil/response.go
  internal/httputil/streaming_test.go
  internal/maps/strings.go
  tests/regression/issue_12865_test.go
  tests/regression/testdata/issue-12865.json
Labels: enhancement, Tests, Bug fix, Review effort [1-5]: 4

#6524 Revert "[TT-2539] added access/transaction logs"
  .gitignore
  cli/linter/schema.json
  config/config.go
  gateway/handler_error.go
  gateway/handler_error_test.go
  gateway/handler_success.go
  gateway/handler_success_test.go
  gateway/middleware.go
  internal/crypto/hash.go
  internal/crypto/token.go
  internal/httputil/Taskfile.yml
  internal/httputil/accesslog/access_log.go
  internal/httputil/accesslog/access_log_test.go
  storage/alias.go
  storage/storage.go
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#6523 [TT-13098] [master] exp/modcheck: Update go.mod dependencies
  go.mod
  go.sum
Labels: enhancement, dependencies, Review effort [1-5]: 3

#6539 Merging to release-5.6: [TT-13098] exp/modcheck: Update go.mod dependencies (#6523)
  go.mod
  go.sum
Labels: enhancement, dependencies, Review effort [1-5]: 3

#6231 [TT-13109]Generate New Swagger and Update Validator for Gateway
  .github/workflows/lint-swagger.yml
  .redocly.lint-ignore.yaml
  docs/swagger.md
  redocly.yml
  swagger.yml
Labels: Review effort [1-5]: 2, Documentation

#6541 Merging to release-5.6: [TT-13109]Generate New Swagger and Update Validator for Gateway (#6231)
  .github/workflows/lint-swagger.yml
  .redocly.lint-ignore.yaml
  docs/swagger.md
  redocly.yml
  swagger.yml
Labels: enhancement, Review effort [1-5]: 3, Documentation

#6543 Merging to release-5.6.0: [TT-13109]Generate New Swagger and Update Validator for Gateway (#6231)
  .github/workflows/lint-swagger.yml
  .redocly.lint-ignore.yaml
  docs/swagger.md
  redocly.yml
  swagger.yml
Labels: enhancement, Review effort [1-5]: 3, Documentation

#6531 [TT-13107] [release-5.6] remove verbose error log
  gateway/session_manager.go
Labels: Review effort [1-5]: 1, Bug fix

#6530 [TT-13107] [release-5.3] remove verbose error log
  gateway/session_manager.go
Labels: Review effort [1-5]: 1, Bug fix

#6544 [TT-13036] A struct is needed to resemble the info section inside of x-tyk-streaming.
  gateway/mw_streaming.go
Labels: enhancement, Review effort [1-5]: 3

#6528 [TT-13107] Remove verbose error logging if quota is disabled
  gateway/session_manager.go
Labels: Review effort [1-5]: 1, Bug fix

#6550 Merging to release-5.6: [TT-13122] build multiarch image on 1.22-bullseye (#6549)
  .github/workflows/release.yml
Labels: enhancement, Review effort [1-5]: 1

#6552 Merging to release-5.6.0: [TT-13107] [release-5.6] remove verbose error log (#6531)
  gateway/session_manager.go
Labels: Review effort [1-5]: 1, Bug fix

#6553 [TT-13098/TT-13107] Backport/release 5.3/release 5.3.6 cherrypick
  gateway/reverse_proxy_test.go
  gateway/session_manager.go
  go.mod
  go.sum
Labels: enhancement, dependencies, Review effort [1-5]: 3

#6535 Fix using broker
  gateway/mw_streaming.go
  gateway/mw_streaming_test.go
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#6555 [TT-13128] Updated description for prefix and suffix matching config options
  config/config.go
Labels: Review effort [1-5]: 1, Documentation

#6558 Merging to release-5.6: [TT-13128] Updated description for prefix and suffix matching config options (#6555)
  config/config.go
Labels: Review effort [1-5]: 2, Documentation

#6556 Merging to release-5.3: [TT-13128] Updated description for prefix and suffix matching config options (#6555)
  config/config.go
Labels: Review effort [1-5]: 2, Documentation

#6557 Merging to release-5.3.6: [TT-13128] Updated description for prefix and suffix matching config options (#6555)
  config/config.go
Labels: Review effort [1-5]: 2, Documentation

#6564 [TT-13087] Adjust example gateway config, to have match preficing explicit by default
  tyk.conf.example
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#6565 Merging to release-5.6: [TT-13087] Adjust example gateway config, to have match preficing explicit by default (#6564)
  tyk.conf.example
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#6566 Merging to release-5.6.0: [TT-13087] Adjust example gateway config, to have match preficing explicit by default (#6564)
  tyk.conf.example
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#6567 Merging to release-5.3: [TT-13087] Adjust example gateway config, to have match preficing explicit by default (#6564)
  tyk.conf.example
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#6569 Merging to release-5.5: [TT-13087] Adjust example gateway config, to have match preficing explicit by default (#6564)
  tyk.conf.example
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#6570 Merging to release-5.5.1: [TT-13087] Adjust example gateway config, to have match preficing explicit by default (#6564)
  tyk.conf.example
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#6574 TT-13130 only mark the wg as done when the connection is stablished
  rpc/rpc_client.go
Labels: Review effort [1-5]: 2, Bug fix

#6576 Merging to release-5.3: TT-13130 only mark the wg as done when the connection is stablished (#6574)
  rpc/rpc_client.go
Labels: Review effort [1-5]: 2, Bug fix

#6578 Merging to release-5.6: TT-13130 only mark the wg as done when the connection is stablished (#6574)
  rpc/rpc_client.go
Labels: Review effort [1-5]: 2, Bug fix

#6579 Merging to release-5.6.0: TT-13130 only mark the wg as done when the connection is stablished (#6574)
  rpc/rpc_client.go
Labels: Review effort [1-5]: 2, Bug fix

#6580 [SYSE-394 release-5.3] Fix test code base for Tyk-Analytics PRs
  .github/workflows/release.yml
  ci/Dockerfile.distroless
  ci/Dockerfile.std
Labels: enhancement, Review effort [1-5]: 3, configuration changes

#6577 Merging to release-5.3.6: TT-13130 only mark the wg as done when the connection is stablished (#6574)
  rpc/rpc_client.go
Labels: Review effort [1-5]: 2, Bug fix

#6571 Merging to release-5.3.5: [TT-13087] Adjust example gateway config, to have match preficing explicit by default (#6564)
  tyk.conf.example
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#6511 [TT-12893]: Adding first implementation of streams API
  .gitignore
  apidef/oas/linter_test.go
  benthos.yaml
  cli/linter/schema.json
  config/config.go
  gateway/api_definition.go
  gateway/api_loader.go
  gateway/middleware.go
  gateway/mw_context_vars.go
  gateway/mw_context_vars_test.go
  gateway/mw_streaming.go
  gateway/mw_streaming_test.go
  gateway/testutil.go
  go.mod
  go.sum
  internal/graphql/graphql_request.go
  internal/graphql/graphql_request_test.go
  internal/graphql/otel_graphql_engine_detailed_test.go
  internal/portal/portal_client.go
  internal/portal/portal_output.go
  internal/portal/portal_output_test.go
  internal/portal/portal_test.go
  internal/streaming/manager.go
  internal/streaming/manager_test.go
Labels: enhancement, Tests, Review effort [1-5]: 4

#6585 [TT-13175] Refactor apply policies test
  gateway/policy_test.go
  internal/policy/apply_test.go
  internal/policy/testdata/policies.json
Labels: Tests, Review effort [1-5]: 4

#6587 [TT-13175] add t.helper to helper functions
  internal/policy/apply_test.go
Labels: Tests, Review effort [1-5]: 2

#6586 [TT-13176]: update graqhql go tools
  go.mod
  go.sum
Labels: enhancement, dependencies, Review effort [1-5]: 3

#6560 [TT-13136] Adjust concurrency group to CI tests, extend to all workflows
  .github/workflows/api-changes.yml
  .github/workflows/ci-tests.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/jira-lint.yml
  .github/workflows/lint-swagger.yml
  .github/workflows/lint.yml
  .github/workflows/plugin-compiler-build.yml
  .github/workflows/release.yml
  .github/workflows/update-oas-docs.yml
Labels: enhancement, Tyk Product Development, Task, Review effort [1-5]: 2, configuration changes

#6591 [TT-13176]: update gql tools
  go.mod
  go.sum
Labels: enhancement, dependencies, Review effort [1-5]: 2
