Repository TykTechnologies/tyk, pull requests merged in 2024-06, with the labels that each got.

#6321 [TT-12186] Fixes TestOAS_ExtractTo_ResetAPIDefinition with a valid event config
  apidef/oas/oas_test.go
Labels: Tests, Review effort [1-5]: 2, Bug fix

#6323 [TT-12312] update openapi spec version
  swagger.yml
Labels: enhancement, Review effort [1-5]: 1, Documentation

#6325 Merging to release-5.4.0: [TT-12312] update openapi spec version (#6323)
  swagger.yml
Labels: enhancement, Review effort [1-5]: 1, Documentation

#6326 [TT-12313, TT-12222] Update graphql-go-tools
  go.mod
  go.sum
Labels: dependencies, Review effort [1-5]: 1

#6327 Merging to release-5.4: [TT-12313, TT-12222] Update graphql-go-tools (#6326)
  go.mod
  go.sum
Labels: dependencies, Review effort [1-5]: 1

#6334 [TT-12323] fix panic when webhook handler is disabled
  gateway/event_handler_webhooks.go
  gateway/event_handler_webhooks_test.go
Labels: Tests, Review effort [1-5]: 2, Bug fix

#6341 Merging to release-5.4.0: [TT-12323] fix panic when webhook handler is disabled (#6334)
  gateway/event_handler_webhooks.go
  gateway/event_handler_webhooks_test.go
Labels: Tests, Review effort [1-5]: 2, Bug fix

#6340 Merging to release-5.4: [TT-12323] fix panic when webhook handler is disabled (#6334)
  gateway/event_handler_webhooks.go
  gateway/event_handler_webhooks_test.go
Labels: Tests, Review effort [1-5]: 2, Bug fix

#6337 [TT-12311] exp/modcheck: Update go.mod dependencies
  gateway/reverse_proxy_test.go
  go.mod
  go.sum
Labels: dependencies, Review effort [1-5]: 2

#6347 [TT-12365] Add new events to validate in x-tyk-api-gateway
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: enhancement, Review effort [1-5]: 1

#6348 Merging to release-5.4: [TT-12365] Add new events to validate in x-tyk-api-gateway (#6347)
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: enhancement, Review effort [1-5]: 1

#6349 Merging to release-5.4.0: [TT-12365] Add new events to validate in x-tyk-api-gateway (#6347)
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: enhancement, Review effort [1-5]: 1

#6345 [TT-9864] Optimize the creation/usage of AST documents
  go.mod
  go.sum
  internal/graphengine/engine_v2.go
Labels: enhancement, dependencies, Review effort [1-5]: 2

#6346 [TT-12285] Add smoothing, fix duplicate x-go-name
  apidef/rate_limit_smoothing.go
  swagger.yml
Labels: enhancement, Review effort [1-5]: 3, Documentation

#6351 Merging to release-5.4: [TT-12285] Add smoothing, fix duplicate x-go-name (#6346)
  apidef/rate_limit_smoothing.go
  swagger.yml
Labels: enhancement, Review effort [1-5]: 3, Documentation

#6352 Merging to release-5.4.0: [TT-12285] Add smoothing, fix duplicate x-go-name (#6346)
  apidef/rate_limit_smoothing.go
  swagger.yml
Labels: enhancement, Review effort [1-5]: 3, Documentation

#6353 TT-12347 fix management of custom keys in mdcb installations
  gateway/auth_manager.go
  gateway/auth_manager_test.go
  gateway/rpc_storage_handler.go
  gateway/rpc_storage_handler_test.go
Labels: enhancement, Review effort [1-5]: 2

#6356 Merging to release-5.4: TT-12347 fix management of custom keys in mdcb installations (#6353)
  gateway/auth_manager.go
  gateway/auth_manager_test.go
  gateway/rpc_storage_handler.go
  gateway/rpc_storage_handler_test.go
Labels: enhancement, Tests, Review effort [1-5]: 3

#6357 Merging to release-5.4.0: TT-12347 fix management of custom keys in mdcb installations (#6353)
  gateway/auth_manager.go
  gateway/auth_manager_test.go
  gateway/rpc_storage_handler.go
  gateway/rpc_storage_handler_test.go
Labels: enhancement, Tests, Review effort [1-5]: 4

#6359 Merging to release-5.3: TT-12347 fix management of custom keys in mdcb installations (#6353)
  gateway/auth_manager.go
  gateway/auth_manager_test.go
  gateway/rpc_storage_handler.go
  gateway/rpc_storage_handler_test.go
Labels: enhancement, Tests, Review effort [1-5]: 4

#6363 [TT-12425] exp/modcheck: Update go.mod dependencies
  go.mod
  go.sum
Labels: enhancement, Review effort [1-5]: 2

#6365 [TT-11762] fix nil err return
  gateway/mw_auth_key.go
Labels: Review effort [1-5]: 1, Bug fix

#6350 [TT-10532] Update taskfile, CI tests
  .github/workflows/ci-tests.yml
  .golangci.yml
  .taskfiles/deps/Taskfile.yml
  .taskfiles/test.yml
  Taskfile.yml
  docker/services/redis.yml
  gateway/rpc_test.go
  gateway/server.go
  storage/redis_cluster_test.go
Labels: enhancement, Tests, Review effort [1-5]: 4

#6369 [TT-10532] Fix golangci-lint step to exit 0
  .github/workflows/ci-tests.yml
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#6251 [DX-1084] Add documentation to protobuf source code files for review
  .github/workflows/ci-tests.yml
  .gitignore
  Taskfile.yml
  coprocess/Taskfile.yml
  coprocess/bindings/python/coprocess_common_pb2.py
  coprocess/bindings/python/coprocess_mini_request_object_pb2.py
  coprocess/bindings/python/coprocess_object_pb2.py
  coprocess/bindings/python/coprocess_object_pb2_grpc.py
  coprocess/bindings/python/coprocess_response_object_pb2.py
  coprocess/bindings/python/coprocess_return_overrides_pb2.py
  coprocess/bindings/python/coprocess_session_state_pb2.py
  coprocess/bindings/ruby/coprocess_common_pb.rb
  coprocess/bindings/ruby/coprocess_mini_request_object_pb.rb
  coprocess/bindings/ruby/coprocess_object_pb.rb
  coprocess/bindings/ruby/coprocess_response_object_pb.rb
  coprocess/bindings/ruby/coprocess_return_overrides_pb.rb
  coprocess/bindings/ruby/coprocess_session_state_pb.rb
  coprocess/coprocess_common.pb.go
  coprocess/coprocess_mini_request_object.pb.go
  coprocess/coprocess_object.pb.go
  coprocess/coprocess_object_grpc.pb.go
  coprocess/coprocess_response_object.pb.go
  coprocess/coprocess_return_overrides.pb.go
  coprocess/coprocess_session_state.pb.go
  coprocess/proto/Taskfile.yml
  coprocess/proto/coprocess_common.proto
  coprocess/proto/coprocess_mini_request_object.proto
  coprocess/proto/coprocess_object.proto
  coprocess/proto/coprocess_response_object.proto
  coprocess/proto/coprocess_return_overrides.proto
  coprocess/proto/coprocess_session_state.proto
  coprocess/python/proto/coprocess_common_pb2.py
  coprocess/python/proto/coprocess_mini_request_object_pb2.py
  coprocess/python/proto/coprocess_object_pb2.py
  coprocess/python/proto/coprocess_object_pb2_grpc.py
  coprocess/python/proto/coprocess_response_object_pb2.py
  coprocess/python/proto/coprocess_return_overrides_pb2.py
  coprocess/python/proto/coprocess_session_state_pb2.py
Labels: enhancement, Review effort [1-5]: 3, Documentation

#6367 [TT-12454] Extract ApplyPolicies into internal/policy scope
  gateway/api.go
  gateway/gateway.go
  gateway/middleware.go
  gateway/mw_rate_limiting.go
  gateway/policy_test.go
  gateway/rpc_storage_handler.go
  gateway/server.go
  gateway/server_test.go
  internal/event/event.go
  internal/event/event_test.go
  internal/policy/Taskfile.yml
  internal/policy/apply.go
  internal/policy/apply_test.go
  internal/policy/store.go
  internal/policy/util.go
  user/session.go
  user/session_test.go
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#6371 Merging to release-5.4.0: [TT-12454] Extract ApplyPolicies into internal/policy scope (#6367)
  gateway/api.go
  gateway/gateway.go
  gateway/middleware.go
  gateway/mw_rate_limiting.go
  gateway/policy_test.go
  gateway/rpc_storage_handler.go
  gateway/server.go
  gateway/server_test.go
  internal/event/event.go
  internal/event/event_test.go
  internal/policy/Taskfile.yml
  internal/policy/apply.go
  internal/policy/apply_test.go
  internal/policy/store.go
  internal/policy/util.go
  user/session.go
  user/session_test.go
Labels: enhancement, Tests, Bug fix, Review effort [1-5]: 4

#6372 Merging to release-5.4: [TT-12454] Extract ApplyPolicies into internal/policy scope (#6367)
  gateway/api.go
  gateway/gateway.go
  gateway/middleware.go
  gateway/mw_rate_limiting.go
  gateway/policy_test.go
  gateway/rpc_storage_handler.go
  gateway/server.go
  gateway/server_test.go
  internal/event/event.go
  internal/event/event_test.go
  internal/policy/Taskfile.yml
  internal/policy/apply.go
  internal/policy/apply_test.go
  internal/policy/store.go
  internal/policy/util.go
  user/session.go
  user/session_test.go
Labels: enhancement, Tests, Bug fix, Review effort [1-5]: 4

#6373 fix unnecessary call to DeleteRawKey if no allowance scope is defined
  gateway/auth_manager.go
  gateway/auth_manager_test.go
Labels: Tests, Review effort [1-5]: 2, Bug fix

#6374 Merging to release-5.4: fix unnecessary call to DeleteRawKey if no allowance scope is defined (#6373)
  gateway/auth_manager.go
  gateway/auth_manager_test.go
Labels: Tests, Bug fix, Review effort [1-5]: 3

#6375 Merging to release-5.3: fix unnecessary call to DeleteRawKey if no allowance scope is defined (#6373)
  gateway/auth_manager.go
  gateway/auth_manager_test.go
Labels: Tests, Review effort [1-5]: 2, Bug fix

#6379 Remove redis5 in CI pipeline
  .github/workflows/ci-tests.yml
Labels: enhancement, Review effort [1-5]: 2, configuration changes
