Repository TykTechnologies/tyk, pull requests merged in 2024-05, with the labels that each got.

#6257 [TT-11991]: added request_headers_rewrite
  apidef/adapter/asyncapi_test.go
  apidef/adapter/openapi_test.go
  apidef/api_definitions.go
  apidef/oas/oas_test.go
  apidef/schema.go
Labels: enhancement, Review effort [1-5]: 2

#6258 [TT-11966/TT-12064] implement OAS webhooks events
  apidef/api_definitions.go
  apidef/migration.go
  apidef/migration_test.go
  apidef/oas/linter_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/server.go
  apidef/oas/server_test.go
  config/config.go
  gateway/coprocess_events.go
  gateway/event_handler_webhooks.go
  gateway/event_handler_webhooks_test.go
  gateway/event_system.go
  gateway/jsvm_event_handler.go
  internal/event/event.go
  internal/reflect/reflect.go
  internal/reflect/reflect_test.go
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#6261 [TT-12064]Update Cast function signature
  apidef/api_definitions.go
  apidef/oas/server.go
  apidef/oas/server_test.go
  internal/reflect/reflect.go
  internal/reflect/reflect_test.go
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#6264 [TT-10291]: upgrade gql-tools for v2
  go.mod
  go.sum
Labels: enhancement, Review effort [1-5]: 2

#6265 readable duration
  apidef/oas/event.go
  apidef/oas/event_test.go
  apidef/oas/linter_test.go
  apidef/oas/time.go
  apidef/oas/upstream.go
  apidef/oas/upstream_test.go
  internal/time/duration.go
  internal/time/duration_test.go
Labels: enhancement, Review effort [1-5]: 3

#6263 [TT-11966/TT-12064] refactor oas events, update contract
  .gitignore
  apidef/oas/event.go
  apidef/oas/event_test.go
  apidef/oas/header.go
  apidef/oas/header_test.go
  apidef/oas/linter_test.go
  apidef/oas/middleware.go
  apidef/oas/operation.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/server.go
  apidef/oas/server_test.go
  apidef/oas/time.go
  apidef/oas/upstream.go
  apidef/oas/upstream_test.go
  internal/event/event.go
  internal/time/duration.go
  internal/time/duration_test.go
Labels: enhancement, Review effort [1-5]: 3

#6266 [TT-11966/TT-12064] update typo in cooldown period
  apidef/oas/event.go
  apidef/oas/event_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: Review effort [1-5]: 1, Bug fix

#6267 [TT-11966/TT-12064] handle edge case with empty event handlers
  apidef/oas/event.go
  apidef/oas/event_test.go
Labels: Tests, Bug fix, Review effort [1-5]: 3

#6268 [TT-12114]update goerr113 with err113
  .golangci.yml
Labels: enhancement, Review effort [1-5]: 1, configuration changes

#6271 [SYSE-363 release-5.3] May template application
  .github/workflows/release.yml
  ci/Dockerfile.distroless
Labels: enhancement, Tests, Review effort [1-5]: 4

#6270 [SYSE-363 master] May template application
  .github/workflows/release.yml
  ci/Dockerfile.distroless
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#6274 update graphql-go-tools
  go.mod
  go.sum
Labels: enhancement, Review effort [1-5]: 1

#6243 [TT-5790] Update EnsureTransport and related tests
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
Labels: enhancement, Tests, Review effort [1-5]: 3

#6278 Merging to release-5.3: [TT-5790] Update EnsureTransport and related tests (#6243)
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#6276 update graphql-go-tools (TT-9884)
  apidef/adapter/asyncapi.go
  apidef/adapter/openapi.go
  go.mod
  go.sum
Labels: enhancement, Review effort [1-5]: 1

#6277 [TT-11990] Change default behaviour of request_headers
  gateway/mw_graphql_test.go
  internal/graphengine/transport.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#6281 [TT-11954/TT-12155] add x-tyk-api-gateway.servers.contextVariables.enabled
  apidef/oas/oas_test.go
  apidef/oas/root.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/server.go
  apidef/oas/server_test.go
  gateway/api.go
  gateway/api_test.go
Labels: enhancement, Review effort [1-5]: 3

#6285 [TT-11954/TT-12115]fix location of contextVariables
  apidef/oas/default.go
  apidef/oas/default_test.go
  apidef/oas/middleware.go
  apidef/oas/middleware_test.go
  apidef/oas/oas.go
  apidef/oas/oas_test.go
  apidef/oas/root.go
  apidef/oas/root_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/server.go
  apidef/oas/server_test.go
  gateway/api.go
  gateway/api_test.go
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#6262 [TT-11739] Clean up rate limiting area, decouple GlobalConfig in APISpec
  config/rate_limit.go
  gateway/mw_api_rate_limit.go
  gateway/mw_js_plugin.go
  gateway/mw_js_plugin_test.go
  gateway/mw_organisation_activity.go
  gateway/mw_rate_limiting.go
  gateway/server.go
  gateway/session_manager.go
  internal/rate/limiter.go
  internal/rate/limiter/limiter.go
  internal/rate/limiter/limiter_fixed_window.go
  internal/rate/limiter/limiter_leaky_bucket.go
  internal/rate/limiter/limiter_sliding_window.go
  internal/rate/limiter/limiter_token_bucket.go
  internal/rate/rate.go
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#6287 [TT-11914/TT-12101]Add OAS trafficLogs
  apidef/migration.go
  apidef/migration_test.go
  apidef/oas/default.go
  apidef/oas/default_test.go
  apidef/oas/middleware.go
  apidef/oas/oas_test.go
  apidef/oas/root.go
  apidef/oas/root_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  gateway/api_test.go
Labels: enhancement, Review effort [1-5]: 3

#6282 [Test] Updates for opentelemetry test, use golang_cross in GH build cache key
  .github/workflows/release.yml
  .taskfiles/opentelemetry.yml
  Taskfile.yml
  ci/tests/tracing/Taskfile.yml
  ci/tests/tracing/configs/otelcollector/collector.config.yml
  ci/tests/tracing/configs/tyk.env
  ci/tests/tracing/docker-compose.yml
  ci/tests/tracing/tracetest/Taskfile.yml
Labels: enhancement, Tests, Review effort [1-5]: 3

#6289 [TT-11806] Respect domain and listen path
  .github/workflows/ci-tests.yml
  gateway/api_loader.go
  gateway/api_test.go
  test/http.go
  tests/regression/issue_11806_test.go
  tests/regression/testdata/issue-11806-api-no-domain.json
  tests/regression/testdata/issue-11806-api-with-domain.json
Labels: enhancement, Tests, Review effort [1-5]: 3, bug_fix

#6290 Merging to release-5.3: [TT-11806] Respect domain and listen path (#6289)
  .github/workflows/ci-tests.yml
  gateway/api_loader.go
  gateway/api_test.go
  test/http.go
  tests/regression/issue_11806_test.go
  tests/regression/testdata/issue-11806-api-no-domain.json
  tests/regression/testdata/issue-11806-api-with-domain.json
Labels: enhancement, Tests, Bug fix, Review effort [1-5]: 3

#6294 Merging to release-5.3: [DX-1345] Update config description for inclusive naming project (#6286)
  config/config.go
Labels: enhancement, Review effort [1-5]: 2, Documentation

#6293 [TT-12153]: Fix/complexity checker and granular access checker v3-preview
  internal/graphengine/engine_v3.go
  internal/graphengine/engine_v3_reverse_proxy.go
  internal/graphengine/graphql_go_tools_v2.go
Labels: enhancement, Review effort [1-5]: 3

#6302 [TT-11954/TT-12155] add x-tyk-api-gateway.servers.contextVariables.en…
  apidef/oas/oas_test.go
  apidef/oas/root.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/server.go
  apidef/oas/server_test.go
  gateway/api.go
  gateway/api_test.go
Labels: enhancement, Tests, Review effort [1-5]: 3

#6304 Merging to release-5.3: [TT-11954/TT-12115]fix location of contextVariables (#6285)
  apidef/oas/default.go
  apidef/oas/default_test.go
  apidef/oas/middleware.go
  apidef/oas/middleware_test.go
  apidef/oas/oas.go
  apidef/oas/oas_test.go
  apidef/oas/root.go
  apidef/oas/root_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/server.go
  apidef/oas/server_test.go
  gateway/api.go
  gateway/api_test.go
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#6303 [TT-12193] Fix poor error handling in webhook event templates
  gateway/event_handler_webhooks.go
  gateway/event_handler_webhooks_test.go
Labels: Tests, Review effort [1-5]: 2, Bug fix

#6305 Merging to release-5.3: [TT-12193] Fix poor error handling in webhook event templates (#6303)
  gateway/event_handler_webhooks.go
  gateway/event_handler_webhooks_test.go
Labels: Tests, Review effort [1-5]: 2, Bug fix

#6298 add features section to graphql proxy config
  apidef/adapter/asyncapi_test.go
  apidef/adapter/openapi_test.go
  apidef/api_definitions.go
  apidef/oas/oas_test.go
  apidef/schema.go
Labels: enhancement, Review effort [1-5]: 2

#6310 [TT-12193] Add log for event handler webhook
  gateway/event_handler_webhooks.go
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#6311 Merging to release-5.3: [TT-12193] Add log for event handler webhook (#6310)
  gateway/event_handler_webhooks.go
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#6312 [TT-12193] Update error handling on webhook events when the event template has errors
  gateway/event_handler_webhooks.go
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#6313 Merging to release-5.3: [TT-12193] Update error handling on webhook events when the event template has errors (#6312)
  gateway/event_handler_webhooks.go
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#6306 [TT-11997] Backend logic for request_headers_rewrite
  gateway/mw_graphql_test.go
  gateway/reverse_proxy.go
  internal/graphengine/engine.go
  internal/graphengine/graphql_go_tools_v1.go
  internal/graphengine/graphql_go_tools_v2.go
  internal/graphengine/transport.go
Labels: enhancement, Tests, Review effort [1-5]: 3

#6296 [TT-12095] Fixing unhashed API keys exposed in OTEL spans
  gateway/mw_auth_key.go
  gateway/mw_oauth2_key_exists.go
Labels: Review effort [1-5]: 2, Bug fix

#6314 Merging to release-5.3.2: [TT-12095] Fixing unhashed API keys exposed in OTEL spans (#6296)
  gateway/mw_auth_key.go
  gateway/mw_oauth2_key_exists.go
Labels: Review effort [1-5]: 2, Bug fix

#6229 [TT-11470] Add human identifiable information in NodeData
  apidef/rpc.go
  gateway/rpc_storage_handler.go
  gateway/rpc_storage_handler_test.go
  gateway/server.go
  gateway/server_test.go
  internal/model/host_details.go
  internal/netutil/ip_address.go
  internal/netutil/ip_address_test.go
  test/buffered_logger.go
  test/buffered_logger_test.go
Labels: enhancement, Tests, Review effort [1-5]: 4

#6316 [TT-11997] Header case insensitivity
  gateway/mw_graphql_test.go
  gateway/reverse_proxy.go
  internal/graphengine/transport.go
Labels: Tests, Bug fix, Review effort [1-5]: 3

#6318 [TT-11739] Re-add gateway.RateLimitExceeded (Dashboard coupling)
  gateway/event_system.go
Labels: Review effort [1-5]: 1, Bug fix

#6319 [TT-11739] Fix RateLimitExceeded var name to include Event prefix
  gateway/event_system.go
Labels: Review effort [1-5]: 1, Bug fix

#6308 feat/TT-9462/tag-cached-response
  gateway/coprocess.go
  gateway/handler_success.go
  gateway/mw_go_plugin.go
  gateway/mw_redis_cache.go
  gateway/mw_virtual_endpoint.go
Labels: enhancement, Review effort [1-5]: 2
