Repository TykTechnologies/tyk, pull requests merged in 2024-02, with the labels that each got.

#6008 [TT-11168]remove duplicated X-Tyk-DetailedActivityLogs from schema
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: Review effort [1-5]: 1, Bug fix

#6009 update graphql-go-tools (TT-11098)
  go.mod
  go.sum
Labels: enhancement, Review effort [1-5]: 1

#6017 [TT-11057] Set enable context variables true in OAS migration
  apidef/oas/oas.go
  apidef/oas/oas_test.go
Labels: Review effort [1-5]: 2, Bug fix

#6006 [TT-10778/TT-11146] Implement kv replace for vault
  gateway/api_definition.go
  storage/kv/vault.go
Labels: enhancement, Review effort [1-5]: 3

#6021 [TT-11063] Improved clarity of schema validation descriptions
  config/config.go
Labels: Review effort [1-5]: 1, Documentation

#6000 TT-10949 Temporal storage
  .github/workflows/ci-tests.yml
  cli/linter/schema.json
  config/config.go
  gateway/api.go
  gateway/api_definition_test.go
  gateway/api_loader.go
  gateway/api_test.go
  gateway/cert.go
  gateway/coprocess_api.go
  gateway/coprocess_id_extractor_test.go
  gateway/event_handler_webhooks.go
  gateway/gateway_test.go
  gateway/health_check.go
  gateway/host_checker_manager_test.go
  gateway/mw_auth_key_test.go
  gateway/mw_external_oauth.go
  gateway/mw_jwt.go
  gateway/mw_organisation_activity_test.go
  gateway/mw_redis_cache_test.go
  gateway/oauth_manager.go
  gateway/oauth_manager_test.go
  gateway/redis_logrus_hook.go
  gateway/redis_signals.go
  gateway/rpc_backup_handlers.go
  gateway/rpc_storage_handler.go
  gateway/rpc_test.go
  gateway/server.go
  gateway/testutil.go
  go.mod
  go.sum
  internal/rate/sliding_log_test.go
  rpc/synchronization_forcer.go
  rpc/synchronization_forcer_test.go
  storage/connection_handler.go
  storage/connection_handler_test.go
  storage/redis_cluster.go
  storage/redis_cluster_test.go
  storage/redis_controller.go
  storage/redis_controller_test.go
Labels: enhancement, Review effort [1-5]: 4

#6025 [TT-5214/TT-11194] update customDomain.name schema
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: enhancement, Review effort [1-5]: 1

#6022 TT-11067, corrected CircuitBreaker half-opened feature JSON tag
  apidef/oas/middleware.go
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: Review effort [1-5]: 1, Bug fix

#6026 TT-10949 Storage v1.2.2
  go.mod
  go.sum
Labels: Review effort [1-5]: 1, bug_fix

#6030 [TT-11177] fix externalOAuth.cache.timeout schema
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: Review effort [1-5]: 1, bug_fix

#6031 [TT-5214/TT-11083] update customDomain.name schema to be of simple string
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: enhancement, Review effort [1-5]: 1

#6034 TT-11135, correctly validate URL rewrite key field
  apidef/oas/linter_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: enhancement, Review effort [1-5]: 2

#6036 [TT-11206] Prevent virtual endpoint panic
  apidef/migration.go
  apidef/migration_test.go
Labels: Review effort [1-5]: 1, bug_fix

#6038 [TT-11178] add omitempty for externalOAuth.providers[*].introspection.cache
  apidef/oas/security.go
Labels: Review effort [1-5]: 1, bug_fix

#6039 [TT-11069] Update graphql-go-tools
  go.mod
  go.sum
Labels: enhancement, Review effort [1-5]: 1

#6028 [TT-11091] Fix custom ratelimit hashed keys
  gateway/mw_api_rate_limit.go
  gateway/mw_organisation_activity.go
  gateway/mw_rate_limiting.go
  gateway/mw_rate_limiting_test.go
  gateway/session_manager.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#6040 [TT-11244]consider named regex while updating OAS servers
  apidef/oas/oas.go
  apidef/oas/oas_test.go
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#6041 [TT-11091] Fix ratelimit key calculation for custom keys.
  gateway/mw_rate_limiting_test.go
  gateway/session_manager.go
Labels: Tests, Review effort [1-5]: 4, bug_fix

#6043 [TT-11260] GraphQL introspection impossible if Allow List is enabled
  internal/graphengine/graphql_go_tools_v1.go
  internal/graphengine/graphql_go_tools_v1_test.go
Labels: Tests, Review effort [1-5]: 2, bug_fix

#6046 [TT-11269] update swagger version to v5.3.0
  swagger.yml
Labels: enhancement, Review effort [1-5]: 1

#6032 [DX-1045]fix integer format issue issue
  swagger.yml
Labels: Review effort [1-5]: 1, bug_fix

#6053 [TT-11249] Update graphql-go-tools
  go.mod
  go.sum
Labels: enhancement, Review effort [1-5]: 1

#6052 Revert "[DX-1045]fix integer format issue issue"
  swagger.yml
Labels: enhancement, Review effort [1-5]: 2

#6059 [TT-11244] update AddServers
  apidef/oas/oas.go
  apidef/oas/oas_test.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#6063 [TT-11348] fix inverted logic for detailed activity logs
  apidef/oas/oas_test.go
  apidef/oas/server.go
Labels: Review effort [1-5]: 2, bug_fix

#6062 [TT-11274] update condition to reload spec
  gateway/util.go
  gateway/util_test.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#6068 [TT-10041] Correctly setting TTL in buildNodeInfo()
  config/config.go
  gateway/health_check.go
  gateway/rpc_storage_handler.go
  gateway/rpc_storage_handler_test.go
  gateway/server.go
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#6073 [TT-11371] Move leaky-bucket behind the dev build flag (5.3.0)
  cli/linter/schema.json
  config/development.go
  config/rate_limit.go
  gateway/mw_rate_limiting_test.go
  internal/rate/rate_nodev.go
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#6078 [TT-11405] Updating JSON tags and field names for TLS max and min versions
  config/config.go
  storage/connection_handler.go
Labels: enhancement, Review effort [1-5]: 2

#6083 Merging to release-5.3.0: [TT-11405] Updating JSON tags and field names for TLS max and min versions (#6078)
  config/config.go
  storage/connection_handler.go
Labels: enhancement, Review effort [1-5]: 2
