Repository TykTechnologies/tyk, pull requests merged in 2024-12, with the labels that each got.

#6732 [TT-13439] update response content-length when response body is modified by coprocess response hook
  coprocess/grpc/coprocess_grpc_test.go
  gateway/coprocess.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 2

#6735 [TT-13670] Decouple OAuthManager behind interface
  gateway/api.go
  gateway/api_definition.go
  gateway/model_apispec.go
  gateway/model_urlspec.go
  gateway/mw_jwt.go
  gateway/mw_oauth2_key_exists.go
  gateway/oauth_manager.go
  gateway/oauth_manager_test.go
  gateway/rpc_storage_handler_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 3

#6737 Merging to release-5.3: [TT-13439] update response content-length when response body is modified by coprocess response hook (#6732)
  coprocess/grpc/coprocess_grpc_test.go
  gateway/coprocess.go
Labels: Review effort [1-5]: 2

#6739 [TT-13390] Silently skip loading bundle on managment node
  config/config.go
  gateway/coprocess_bundle.go
  gateway/coprocess_bundle_test.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 2

#6743 Merging to release-5.3: [TT-13390] Silently skip loading bundle on managment node (#6739)
  config/config.go
  gateway/coprocess_bundle.go
  gateway/coprocess_bundle_test.go
Labels: Review effort [1-5]: 2

#6733 [TT-13669] Add pre-commit, pre-push hooks
  .taskfiles/deps/Taskfile.yml
  .taskfiles/hooks.yml
  .taskfiles/lint.yml
  CONTRIBUTING.md
  Taskfile.yml
  lefthook.yml
Labels: Tyk Product Development, Task, Review effort [1-5]: 2

#6742 Merging to release-5.7: [TT-13390] Silently skip loading bundle on managment node (#6739)
  config/config.go
  gateway/coprocess_bundle.go
  gateway/coprocess_bundle_test.go
Labels: Review effort [1-5]: 2

#6727 [TT-13142] Fix panic when detailed analytics is turned on with SSE streaming
  gateway/handler_success.go
  gateway/reverse_proxy_test.go
  gateway/testutil.go
  go.mod
  go.sum
  internal/graphql/otel_graphql_engine_detailed_test.go
Labels: Review effort [1-5]: 2

#6736 [TT-13695] Testing fixes, skip dangerous tests
  .gitignore
  Taskfile.yml
  gateway/api_test.go
  gateway/gateway_test.go
  gateway/host_checker_test.go
  gateway/middleware_test.go
  gateway/mw_auth_key_test.go
  gateway/mw_external_oauth_test.go
  gateway/mw_organisation_activity_test.go
  gateway/mw_rate_limiting_test.go
  gateway/mw_streaming_test.go
  gateway/rpc_storage_handler_test.go
  gateway/rpc_test.go
  test/util.go
Labels: Tyk Product Development, Task

#6749 [testing/gha] Cache is handled by setup/go, this blocks
  .github/workflows/ci-tests.yml
Labels: Review effort [1-5]: 1

#6360 [DX-1423] Update TYK_GW_SECRETS definition
  config/config.go
  config/config_test.go
Labels: bug, Review effort [1-5]: 2, Documentation, Developer eXperience

#6746 Merging to release-5.7: [TT-13142] Fix panic when detailed analytics is turned on with SSE streaming (#6727)
  gateway/handler_success.go
  gateway/reverse_proxy_test.go
  gateway/testutil.go
  go.mod
  go.sum
  internal/graphql/otel_graphql_engine_detailed_test.go
Labels: Review effort [1-5]: 2

#6734 [TT-12775] Request size limit breaks GET and DELETE requests
  gateway/mw_request_size_limit.go
  gateway/mw_request_size_limit_test.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 2

#6751 [TT-12775] Add request size limit test for POST, PUT and PATCH methods.
  gateway/mw_request_size_limit_test.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 2

#6754 Merging to release-5.3: [TT-12775] Request size limit breaks GET and DELETE requests (#6734)
  gateway/mw_request_size_limit.go
  gateway/mw_request_size_limit_test.go
Labels: Review effort [1-5]: 2

#6755 Merging to release-5.3: [TT-12775] Add request size limit test for POST, PUT and PATCH methods. (#6751)
  gateway/mw_request_size_limit_test.go
Labels: Review effort [1-5]: 2

#6473 [TT-12710]deleting All Partitioned Policies a Key is linked to does not delete the Key
  gateway/api_test.go
  gateway/multiauth_test.go
  gateway/mw_jwt_test.go
  gateway/server.go
  gateway/testutil.go
  internal/policy/apply.go
  internal/policy/apply_test.go
Labels: Review effort [1-5]: 2, Bug fix

#6761 Fixing Race Condition in CI
  storage/redis_cluster_test.go
Labels: Review effort [1-5]: 2

#6747 Merging to release-5.3: [TT-13142] Fix panic when detailed analytics is turned on with SSE streaming (#6727)
  gateway/handler_success.go
  gateway/reverse_proxy_test.go
  gateway/testutil.go
  go.mod
  go.sum
  internal/graphql/otel_graphql_engine_detailed_test.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 3

#6763 Merging to release-5.3.9: Fixing Race Condition in CI (#6761)
  storage/redis_cluster_test.go
Labels: Review effort [1-5]: 2

#6744 [TT-13155] Explicitly copy BaseMiddleware for each middleware that takes it
  .taskfiles/test.yml
  coprocess/Taskfile.yml
  coprocess/grpc/coprocess_grpc_test.go
  coprocess/grpc/dispatcher_test.go
  coprocess/grpc/services_test.go
  dnscache/storage_test.go
  gateway/api_loader.go
  gateway/coprocess.go
  gateway/coprocess_id_extractor.go
  gateway/coprocess_test.go
  gateway/gateway_test.go
  gateway/middleware.go
  gateway/middleware_wrap.go
  gateway/mw_go_plugin.go
  gateway/testutil.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 3

#6759 Merging to release-5.3.9: [TT-13507] Fix for custom domains with substring listen path (#6705)
  docker/services/httpbin.yml
  gateway/api_loader.go
  gateway/api_loader_test.go
Labels: Review effort [1-5]: 2

#6740 TT-13513 TT-12767 TT-12768 ensure to save oauth clients locally when pulled from rpc
  certs/manager.go
  gateway/server.go
  storage/mdcb_storage.go
  storage/mdcb_storage_test.go
  storage/mock/storage.go
  storage/storage.go
Labels: Review effort [1-5]: 4

#6762 [TT-13715] Upgrade to Bento v1.4.0
  go.mod
  go.sum
Labels: bug, Tyk Product Development, Review effort [1-5]: 3

#6766 [TT-13608] Issues with custom scalar in query variable
  go.mod
  go.sum
Labels: bug, Tyk Product Development, Review effort [1-5]: 1

#6768 Merging to release-5.3: [TT-13608] Issues with custom scalar in query variable (#6766)
  go.mod
  go.sum
Labels: bug, Tyk Product Development, Review effort [1-5]: 1

#6764 Merging to release-5.3: [TT-13155] Explicitly copy BaseMiddleware for each middleware that takes it (#6744)
  .taskfiles/test.yml
  coprocess/Taskfile.yml
  coprocess/grpc/coprocess_grpc_test.go
  coprocess/grpc/dispatcher_test.go
  coprocess/grpc/services_test.go
  dnscache/storage_test.go
  gateway/api_loader.go
  gateway/coprocess.go
  gateway/coprocess_id_extractor.go
  gateway/coprocess_test.go
  gateway/gateway_test.go
  gateway/middleware.go
  gateway/mw_go_plugin.go
  gateway/testutil.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 4

#6771 Merging to release-5.7: [TT-13155] Explicitly copy BaseMiddleware for each middleware that takes it (#6744)
  .taskfiles/test.yml
  coprocess/Taskfile.yml
  coprocess/grpc/coprocess_grpc_test.go
  coprocess/grpc/dispatcher_test.go
  coprocess/grpc/services_test.go
  dnscache/storage_test.go
  gateway/api_loader.go
  gateway/coprocess.go
  gateway/coprocess_id_extractor.go
  gateway/coprocess_test.go
  gateway/gateway_test.go
  gateway/middleware.go
  gateway/middleware_wrap.go
  gateway/mw_go_plugin.go
  gateway/testutil.go
Labels: Review effort [1-5]: 3

#6770 [TT-13021]Transfer encoding fix
  gateway/mw_url_rewrite.go
  gateway/mw_url_rewrite_test.go
  gateway/mw_validate_json.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 4

#6772 [TT-11711] Fix listenpath validation
  apidef/migration.go
  gateway/api_definition.go
  gateway/api_loader.go
  gateway/api_loader_test.go
  internal/httputil/mux.go
  internal/httputil/mux_test.go
  internal/model/merged_apis.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 4

#6773 Merging to release-5.3: [TT-11711] Fix listenpath validation (#6772)
  apidef/migration.go
  gateway/api_definition.go
  gateway/api_loader.go
  gateway/api_loader_test.go
  internal/httputil/mux.go
  internal/httputil/mux_test.go
  internal/model/merged_apis.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 4

#6776 Merging to release-5.3.9: [TT-13021]Transfer encoding fix (#6770)
  gateway/mw_url_rewrite.go
  gateway/mw_url_rewrite_test.go
  gateway/mw_validate_json.go
Labels: Review effort [1-5]: 4

#6779 Merging to release-5.3: [TT-12710]deleting All Partitioned Policies a Key is linked to does not delete the Key (#6473)
  gateway/api_test.go
  gateway/middleware.go
  gateway/multiauth_test.go
  gateway/mw_jwt_test.go
  gateway/policy_test.go
  gateway/server.go
  gateway/testutil.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 3

#6782 Merging to release-5.7: [TT-13021]Transfer encoding fix (#6770)
  gateway/mw_url_rewrite.go
  gateway/mw_url_rewrite_test.go
  gateway/mw_validate_json.go
Labels: Review effort [1-5]: 4

#6783 Merging to release-5.3: [TT-13021]Transfer encoding fix (#6770)
  gateway/mw_url_rewrite.go
  gateway/mw_url_rewrite_test.go
  gateway/mw_validate_json.go
Labels: Review effort [1-5]: 4

#6368 [TT-12495] Add support for RSASSA-PSS signed JWTs
  gateway/mw_jwt.go
  gateway/mw_jwt_test.go
Labels: enhancement, Tyk Product Development, Story, Tests, Review effort [1-5]: 3

#6784 Merging to release-5.7: [TT-12495] Add support for RSASSA-PSS signed JWTs (#6368)
  gateway/mw_jwt.go
  gateway/mw_jwt_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 3

#6785 Merging to release-5.3: [TT-12495] Add support for RSASSA-PSS signed JWTs (#6368)
  gateway/mw_jwt.go
  gateway/mw_jwt_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 3

#6781 Merging to release-5.7: [TT-12710]deleting All Partitioned Policies a Key is linked to does not delete the Key (#6473)
  gateway/api_test.go
  gateway/multiauth_test.go
  gateway/mw_jwt_test.go
  gateway/server.go
  gateway/testutil.go
  internal/policy/apply.go
  internal/policy/apply_test.go
Labels: Review effort [1-5]: 3

#6787 [TT-13021], fixed missing lines
  gateway/mw_url_rewrite.go
  gateway/mw_validate_json.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 2

#6788 Merging to release-5.7: [TT-13021], fixed missing lines (#6787)
  gateway/mw_url_rewrite.go
  gateway/mw_validate_json.go
Labels: Review effort [1-5]: 2

#6789 Merging to release-5.3: [TT-13021], fixed missing lines (#6787)
  gateway/mw_url_rewrite.go
  gateway/mw_validate_json.go
Labels: Review effort [1-5]: 2

#6778 [TT-12741] Looped ap is wrongfully inherit the caller's authentication key when using url rewrite
  ctx/ctx.go
  docs/diagrams/middleware-looping.png
  gateway/api.go
  gateway/api_loader.go
  gateway/looping_test.go
  gateway/middleware_test.go
  gateway/mw_auth_key.go
  internal/httpctx/looping.go
  internal/httpctx/looping_test.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 4

#6794 [TT-13741] [master] exp/modcheck: Update go.mod dependencies
  go.mod
  go.sum
Labels: Tyk Product Development, Task, Review effort [1-5]: 3

#6793 Merging to release-5.3: [TT-12741] Looped ap is wrongfully inherit the caller's authentication key when using url rewrite (#6778)
  ctx/ctx.go
  docs/diagrams/middleware-looping.png
  gateway/api.go
  gateway/api_loader.go
  gateway/looping_test.go
  gateway/middleware_test.go
  gateway/mw_auth_key.go
  internal/httpctx/context.go
  internal/httpctx/context_test.go
  internal/httpctx/looping.go
  internal/httpctx/looping_test.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 4

#6795 [TT-13741] [release-5.3] exp/modcheck: Update go.mod dependencies
  go.mod
  go.sum
Labels: Review effort [1-5]: 2

#6796 [TT-13741] [release-5.7] exp/modcheck: Update go.mod dependencies
  go.mod
  go.sum
Labels: Tyk Product Development, Task, Review effort [1-5]: 3

#6798 Merging to release-5.3: TT-13513 TT-12767 TT-12768 ensure to save oauth clients locally when pulled from rpc (#6740)
  certs/manager.go
  gateway/server.go
  storage/mdcb_storage.go
  storage/mdcb_storage_test.go
  storage/mock/storage.go
  storage/storage.go
Labels: Review effort [1-5]: 4

#6801 Merging to release-5.3.9: [TT-13741] [release-5.3] exp/modcheck: Update go.mod dependencies (#6795)
  go.mod
  go.sum
Labels: Review effort [1-5]: 2

#6774 [TT-13564] Add classic to OAS translation guide
  docs/dev/apidef-oas.md
Labels: Review effort [1-5]: 2

#6800 Merging to release-5.7.1: [TT-13741] [release-5.7] exp/modcheck: Update go.mod dependencies (#6796)
  go.mod
  go.sum
Labels: Review effort [1-5]: 3

#6799 Merging to release-5.7: TT-13513 TT-12767 TT-12768 ensure to save oauth clients locally when pulled from rpc (#6740)
  certs/manager.go
  gateway/server.go
  storage/mdcb_storage.go
  storage/mdcb_storage_test.go
  storage/mock/storage.go
  storage/storage.go
Labels: Review effort [1-5]: 4

#6802 [TT-13742] update swagger version
  swagger.yml
Labels: Tyk Product Development, Task, Review effort [1-5]: 1

#6803 [TT-13742] Update swagger to 5.7.1
  swagger.yml
Labels: Tyk Product Development, Task, Review effort [1-5]: 1

#6804 Merging to release-5.3.9: [TT-13742] update swagger version (#6802)
  swagger.yml
Labels: Review effort [1-5]: 1

#6797 [TT-13761] add batch request to the latest open api specs
  .redocly.lint-ignore.yaml
  swagger.yml
Labels: Tyk Product Development, Story, Review effort [1-5]: 4, Developer eXperience

#6807 Merging to release-5.7: [TT-13761] add batch request to the latest open api specs (#6797)
  .redocly.lint-ignore.yaml
  swagger.yml
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6808 Merging to release-5.7.1: [TT-13761] add batch request to the latest open api specs (#6797)
  .redocly.lint-ignore.yaml
  swagger.yml
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6810 Merging to release-5.3.9: TT-13513 TT-12767 TT-12768 ensure to save oauth clients locally when pulled from rpc (#6740)
  certs/manager.go
  gateway/server.go
  storage/mdcb_storage.go
  storage/mdcb_storage_test.go
  storage/mock/storage.go
  storage/storage.go
Labels: Review effort [1-5]: 4

#6811 Merging to release-5.7.1: TT-13513 TT-12767 TT-12768 ensure to save oauth clients locally when pulled from rpc (#6740)
  certs/manager.go
  gateway/server.go
  storage/mdcb_storage.go
  storage/mdcb_storage_test.go
  storage/mock/storage.go
  storage/storage.go
Labels: Review effort [1-5]: 4

#6813 [TT-13769] Extend plugin compiler test with arm64 cross build
  ci/tests/plugin-compiler/README.md
  ci/tests/plugin-compiler/Taskfile.yml
  ci/tests/plugin-compiler/test.sh
  ci/tests/plugin-compiler/testdata/qa-plugin/README.md
  ci/tests/plugin-compiler/testdata/qa-plugin/main.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 2

#6814 Merging to release-5.3: [TT-13769] Extend plugin compiler test with arm64 cross build (#6813)
  ci/tests/plugin-compiler/README.md
  ci/tests/plugin-compiler/Taskfile.yml
  ci/tests/plugin-compiler/test.sh
  ci/tests/plugin-compiler/testdata/qa-plugin/README.md
  ci/tests/plugin-compiler/testdata/qa-plugin/main.go
Labels: Review effort [1-5]: 2

#6815 Merging to master: Merging to release-5.3: [TT-13769] Extend plugin compiler test with arm64 cross build (#6813)
  ci/tests/plugin-compiler/README.md
  ci/tests/plugin-compiler/Taskfile.yml
  ci/tests/plugin-compiler/test.sh
  ci/tests/plugin-compiler/testdata/qa-plugin/README.md
  ci/tests/plugin-compiler/testdata/qa-plugin/main.go
Labels: Review effort [1-5]: 2
