Repository TykTechnologies/tyk, pull requests merged in 2024-07, with the labels that each got.

#6377 TT-12306, addressed changes suggested in the tyk-docs PR
  config/rate_limit.go
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#6383 [DX-1473] Replace authorise with authorize
  apidef/oas/authentication.go
  config/config.go
Labels: enhancement, Review effort [1-5]: 1

#6332 [SYSE-370 release-5.3] June template application
  .github/workflows/release.yml
  ci/Dockerfile.std
  ci/bin/unlock-agent.sh
  ci/goreleaser/goreleaser.yml
Labels: enhancement, Review effort [1-5]: 4, configuration changes

#6331 [SYSE-370 master] June template application
  .github/workflows/release.yml
  ci/Dockerfile.distroless
  ci/Dockerfile.std
  ci/bin/unlock-agent.sh
  ci/goreleaser/goreleaser.yml
Labels: enhancement, Review effort [1-5]: 4, configuration changes

#6386 [TT-11032] Godoc CI lint action, config and apidef/oas
  Taskfile.yml
  apidef/oas/Taskfile.yml
  apidef/oas/authentication.go
  apidef/oas/default.go
  apidef/oas/event.go
  apidef/oas/middleware.go
  apidef/oas/oas.go
  apidef/oas/old_oas.go
  apidef/oas/security.go
  apidef/oas/server.go
  apidef/oas/url_rewrite.go
  config/Taskfile.yml
Labels: enhancement, Tests, Review effort [1-5]: 3

#6395 Merging to release-5.3: [TT-11032] Godoc CI lint action, config and apidef/oas (#6386)
  Taskfile.yml
  apidef/oas/Taskfile.yml
  apidef/oas/authentication.go
  apidef/oas/default.go
  apidef/oas/middleware.go
  apidef/oas/oas.go
  apidef/oas/old_oas.go
  apidef/oas/security.go
  apidef/oas/server.go
  apidef/oas/url_rewrite.go
  config/Taskfile.yml
Labels: enhancement, Tests, Review effort [1-5]: 3

#6390 [TT-12503] Render ID type as a String
  go.mod
  go.sum
Labels: enhancement, dependencies, Review effort [1-5]: 1

#6391 [TT-12318] SSE streaming is broken
  Makefile
  docker-compose.yml
  docker/services/.gitignore
  docker/services/docker-compose.yml
  docker/services/httpbin.yml
  gateway/handler_success.go
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
  internal/httputil/streaming.go
Labels: enhancement, Tests, Review effort [1-5]: 4, configuration changes

#6404 [SYSE-370 release-5.3] June template application
  .github/workflows/release.yml
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#6403 [SYSE-370 master] June template application
  .github/workflows/release.yml
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#6410 [SYSE-370 master] June template application
  .github/workflows/release.yml
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#6408 [SYSE-370 release-5.3] June template application
  .github/workflows/release.yml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#6400 [TT-12575] Add coverage to gitignore, add package to regression to fix api changes
  .gitignore
  tests/regression/regression.go
Labels: enhancement, Review effort [1-5]: 1

#6398 Merging to release-5.3: [TT-12318] SSE streaming is broken (#6391)
  Makefile
  gateway/handler_success.go
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
  internal/httputil/streaming.go
Labels: enhancement, Tests, Review effort [1-5]: 4, configuration changes

#6405 [TT-1570/TT-12587]mTLS: allow validating client certificates against root certificate authority
  gateway/cert_test.go
  internal/crypto/helpers.go
  internal/crypto/testutil.go
Labels: enhancement, Tests, Review effort [1-5]: 4

#6406 [TT-1570/TT-12588] extend certs endpoint with is_ca
  certs/manager.go
  gateway/cert_test.go
  swagger.yml
Labels: enhancement, Tests, Review effort [1-5]: 4

#6387 [SYSE-370 release-5.4] June template application
  .github/workflows/release.yml
  ci/Dockerfile.std
  ci/bin/unlock-agent.sh
  ci/goreleaser/goreleaser.yml
Labels: enhancement, Review effort [1-5]: 4, configuration changes

#6396 Merging to release-5.4: [TT-12503] Render ID type as a String (#6390)
  go.mod
  go.sum
Labels: enhancement, dependencies, Review effort [1-5]: 1

#6415 [TT-12618] Refactor/checkspec findspec
  gateway/api_definition.go
  gateway/model_apispec.go
  gateway/model_urlspec.go
Labels: enhancement, Review effort [1-5]: 3, Other

#6413 [TT-12618] Add RateLimit per-path settings to apidefinition classic, add test case
  apidef/api_definitions.go
  apidef/api_definitions_test.go
  gateway/api_definition.go
  gateway/model_urlspec.go
  gateway/mw_api_rate_limit.go
  internal/rate/limiter.go
  tests/rate/per_api_limit_test.go
Labels: enhancement, Tests, Review effort [1-5]: 3

#6416 [TT-12634] Add oas contract and migrations to/from classic apidef
  apidef/oas/event.go
  apidef/oas/event_test.go
  apidef/oas/linter_test.go
  apidef/oas/operation.go
  apidef/oas/operation_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/upstream.go
  apidef/oas/upstream_test.go
Labels: enhancement, Tests, Review effort [1-5]: 3

#6401 [TT-12519], added necessary logic for UrlVersioningPattern
  apidef/api_definitions.go
  apidef/oas/root.go
  apidef/oas/schema/x-tyk-api-gateway.json
  gateway/api_definition.go
  tests/proxy/proxy.go
  tests/proxy/version_routing_test.go
Labels: enhancement, Tests, Review effort [1-5]: 3

#6422 [TT-12587] verify root CA on certificate check mw
  internal/crypto/helpers.go
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#6397 [TT-12195] : Public playground still shows schema when introspection is turned off
  gateway/api_loader.go
  templates/playground/index.html
Labels: Review effort [1-5]: 2, Bug fix

#6421 TT-12380 Fill latency analytics field
  go.mod
  go.sum
  rpc/rpc_analytics_purger.go
  rpc/rpc_analytics_purger_test.go
Labels: enhancement, Review effort [1-5]: 2, Other

#6423 Merging to release-5.3: TT-12380 Fill latency analytics field (#6421)
  go.mod
  go.sum
  rpc/rpc_analytics_purger.go
  rpc/rpc_analytics_purger_test.go
Labels: enhancement, Tests, Review effort [1-5]: 3

#6417 [TT-12635] Update swagger.yml with ExtendedPathsSet.RateLimitMeta
  .github/CODEOWNERS
  internal/build/version.go
  swagger.yml
Labels: enhancement, Review effort [1-5]: 2, Documentation

#6426 Merging to release-5.4: [TT-12195] : Public playground still shows schema when introspection is turned off (#6397)
  gateway/api_loader.go
  templates/playground/index.html
Labels: Review effort [1-5]: 2, Bug fix

#6425 [TT-12688] Ensure OAS API paths get applied to gateway by length, sort by path
  apidef/oas/oasutil.go
  apidef/oas/operation.go
  internal/oasutil/paths.go
  internal/oasutil/paths_test.go
Labels: Tests, Review effort [1-5]: 2, Bug fix

#6428 Merging to release-5.3: [TT-12688] Ensure OAS API paths get applied to gateway by length, sort by path (#6425)
  apidef/oas/oasutil.go
  apidef/oas/operation.go
  internal/oasutil/paths.go
  internal/oasutil/paths_test.go
Labels: Tests, Bug fix, Review effort [1-5]: 3

#6429 [TT-11753] fix thelper.bug.major lint error
  apidef/adapter/gqlengineadapter/utils_test.go
  apidef/adapter/utils_test.go
  apidef/migration_test.go
  apidef/oas/default_test.go
  apidef/oas/root_test.go
  apidef/validator_test.go
  cli/bundler/bundler_test.go
  config/config_test.go
  gateway/api_definition_test.go
  gateway/api_loader_test.go
  gateway/api_test.go
  gateway/cert_go1.10_test.go
  gateway/cert_test.go
  gateway/gateway_test.go
  gateway/grpc_streaming_client_test.go
  gateway/grpc_streaming_server_test.go
  gateway/grpc_test.go
  gateway/handler_success_test.go
  gateway/middleware_test.go
  gateway/multiauth_test.go
  gateway/mw_api_rate_limit_test.go
  gateway/mw_graphql_test.go
  gateway/mw_http_signature_validation_test.go
  gateway/mw_jwt_test.go
  gateway/mw_oas_validate_request_test.go
  gateway/mw_organisation_activity_test.go
  gateway/mw_redis_cache_test.go
  gateway/mw_transform_test.go
  gateway/mw_version_check_test.go
  gateway/oauth_manager_test.go
  gateway/policy_test.go
  gateway/redis_signals_test.go
  gateway/reverse_proxy_test.go
  gateway/testutil.go
  internal/graphengine/engine_v1_test.go
  internal/graphengine/engine_v2_test.go
  internal/graphengine/engine_v3_test.go
  internal/graphengine/graphql_go_tools_v1_test.go
  internal/rate/sliding_log_test.go
  tcp/tcp_test.go
Labels: Review effort [1-5]: 1, Tests, Bug fix

#6430 [TT-12688] extractto to honor sorting
  apidef/oas/operation.go
  apidef/oas/operation_test.go
  apidef/oas/testdata/urlSorting.json
  internal/oasutil/paths_test.go
Labels: enhancement, Tests, Review effort [1-5]: 3

#6431 Merging to release-5.3: [TT-12688] extractto to honor sorting (#6430)
  apidef/oas/operation.go
  apidef/oas/operation_test.go
  apidef/oas/testdata/urlSorting.json
  internal/oasutil/paths_test.go
Labels: enhancement, Tests, Review effort [1-5]: 3

#6203 [TT-11810] Plugin bundles: fix slow tests, improve internal signature verifier API
  gateway/coprocess_bundle.go
  gateway/coprocess_bundle_test.go
  gateway/gateway.go
  gateway/redis_signals.go
  gateway/server.go
  gateway/testutil.go
  tests/coprocess/Taskfile.yml
  tests/coprocess/bundle_loading_test.go
  tests/coprocess/coprocess.go
  tests/coprocess/testdata/bundle.zip
  tests/coprocess/testdata/server-invalid.pub
  tests/coprocess/testdata/server.pub
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#6432 Merging to release-5.3: [TT-11810] Plugin bundles: fix slow tests, improve internal signature verifier API (#6203)
  gateway/coprocess_bundle.go
  gateway/coprocess_bundle_test.go
  gateway/redis_signals.go
  gateway/server.go
  gateway/testutil.go
  tests/coprocess/Taskfile.yml
  tests/coprocess/bundle_loading_test.go
  tests/coprocess/coprocess.go
  tests/coprocess/testdata/bundle.zip
  tests/coprocess/testdata/server-invalid.pub
  tests/coprocess/testdata/server.pub
Labels: enhancement, Tests, Bug fix, Review effort [1-5]: 3

#6433 Merging to release-5.3: [TT-12698] Add linter to gateway to check for named scope conflicts (#6409)
  .taskfiles/lint.yml
  Taskfile.yml
  apidef/adapter/asyncapi.go
  apidef/adapter/gqlengineadapter/adapter_proxy_only.go
  apidef/adapter/gqlengineadapter/adapter_proxy_only_test.go
  apidef/adapter/gqlengineadapter/adapter_supergraph.go
  apidef/adapter/gqlengineadapter/adapter_supergraph_test.go
  apidef/adapter/gqlengineadapter/adapter_udg.go
  apidef/adapter/gqlengineadapter/adapter_udg_test.go
  apidef/adapter/gqlengineadapter/utils.go
  apidef/adapter/gqlengineadapter/utils_engine_v2.go
  apidef/adapter/gqlengineadapter/utils_engine_v2_test.go
  apidef/adapter/gqlengineadapter/utils_test.go
  apidef/api_definitions.go
  apidef/oas/oasutil.go
  gateway/analytics.go
  gateway/api_definition.go
  gateway/api_definition_test.go
  gateway/api_loader.go
  gateway/api_loader_test.go
  gateway/api_test.go
  gateway/event_handler_webhooks.go
  gateway/grpc_streaming_client_test.go
  gateway/grpc_test.go
  gateway/handler_error.go
  gateway/handler_success.go
  gateway/host_checker.go
  gateway/host_checker_test.go
  gateway/mw_auth_key.go
  gateway/mw_auth_key_test.go
  gateway/mw_http_signature_validation_test.go
  gateway/mw_request_signing.go
  gateway/mw_transform_test.go
  gateway/oauth_manager.go
  gateway/policy_test.go
  gateway/redis_signals.go
  gateway/reverse_proxy_test.go
  gateway/rpc_backup_handlers.go
  gateway/rpc_storage_handler.go
  gateway/server.go
  gateway/testutil.go
  internal/redis/redis.go
  storage/kv/consul.go
  storage/kv/consul_test.go
  storage/kv/vault.go
  trace/log.go
  trace/openzipkin/zipkin.go
Labels: enhancement, Tests, Review effort [1-5]: 3

#6434 [TT-11758] fix sonarcloud reported issues on errorlint.bug.major
  cli/bundler/bundler_test.go
  cli/importer/importer.go
  gateway/analytics_go_plugin.go
  gateway/batch_requests.go
  gateway/coprocess_events.go
  gateway/dashboard_register.go
  gateway/grpc_streaming_client_test.go
  gateway/grpc_streaming_server_test.go
  gateway/host_checker.go
  gateway/mock_response.go
  gateway/mw_external_oauth.go
  gateway/mw_oas_validate_request.go
  gateway/mw_transform.go
  gateway/mw_validate_json.go
  gateway/redis_signals.go
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
  internal/graphql/graphql_request.go
  storage/kv/consul_test.go
  storage/redis_cluster_test.go
  tcp/tcp.go
  test/http.go
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#6435 [TT-11758] fix sonarcloud reported issues on errorlint.bug.major
  cli/importer/importer.go
  cli/linter/linter.go
  config/config.go
Labels: Review effort [1-5]: 2, Bug fix

#6436 [DX-1508, DX-1511] Update config.go godoc comments with American spelling conversions
  config/config.go
Labels: Review effort [1-5]: 1, Documentation

#6440 Merging to release-5.3: [DX-1508, DX-1511] Update config.go godoc comments with American spelling conversions (#6436)
  config/config.go
Labels: Review effort [1-5]: 1, Documentation
