Repository TykTechnologies/tyk, pull requests merged in 2024-11, with the labels that each got.

#6689 TT-13271, fix for token metadata not being cached
  gateway/mw_oauth2_auth.go
  gateway/mw_oauth2_auth_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6598 [TT-12885] Add plugin development guide for manual builds
  .vale.ini
  .vale/styles/config/vocabularies/Tyk/accept.txt
  .vale/styles/write-good/Cliches.yml
  .vale/styles/write-good/E-Prime.yml
  .vale/styles/write-good/Illusions.yml
  .vale/styles/write-good/Passive.yml
  .vale/styles/write-good/README.md
  .vale/styles/write-good/So.yml
  .vale/styles/write-good/ThereIs.yml
  .vale/styles/write-good/TooWordy.yml
  .vale/styles/write-good/Weasel.yml
  .vale/styles/write-good/meta.json
  docs/Taskfile.yml
  docs/plugins/go-development-flow.md
  docs/plugins/tests/.gitignore
  docs/plugins/tests/Taskfile.yml
  docs/schemas/swagger.md
Labels: enhancement, Tyk Product Development, Story, Review effort [1-5]: 3, Documentation

#6684 [TT-13391] Move upstream OAuth to EE
  ee/middleware/upstreamoauth/middleware.go
  ee/middleware/upstreamoauth/model.go
  ee/middleware/upstreamoauth/provider.go
  ee/middleware/upstreamoauth/provider_client_credentials.go
  ee/middleware/upstreamoauth/provider_password_authentication.go
  ee/middleware/upstreamoauth/provider_test.go
  ee/middleware/upstreamoauth/token_cache.go
  gateway/api.go
  gateway/api_loader.go
  gateway/api_test.go
  gateway/event_system.go
  gateway/handler_success.go
  gateway/handler_success_test.go
  gateway/middleware.go
  gateway/model.go
  gateway/mw_oauth2_auth.go
  gateway/mw_oauth2_auth_ee.go
  gateway/mw_url_rewrite_test.go
  gateway/reverse_proxy_test.go
  gateway/rpc_backup_handlers.go
  gateway/server.go
  internal/crypto/helpers.go
  internal/event/event.go
  internal/httpctx/context.go
  internal/httpctx/context_test.go
  internal/model/events.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6694 [TT-13375] Improved Upstream Auth validation rules
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: Tyk Product Development, Story, Review effort [1-5]: 3

#6671 add stream analytics to ee (TT-13233)
  ee/middleware/streams/analytics.go
  ee/middleware/streams/manager.go
  ee/middleware/streams/middleware.go
  ee/middleware/streams/util.go
  gateway/analytics_streams.go
  gateway/analytics_streams_test.go
  gateway/handler_success.go
  gateway/mw_streaming_ee.go
  gateway/mw_streaming_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6695 Merging to release-5.3.8: Tt 13476 update gw oas version (#6692)
  swagger.yml
Labels: Review effort [1-5]: 1

#6697 [TT-13508] Streams poor performance when reconnecting to a Streams API
  ee/middleware/streams/manager.go
  go.mod
  go.sum
  internal/graphql/otel_graphql_engine_detailed_test.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 4

#6699 [TT-13422] Do not allow empty string in upstream auth configuration strings
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/upstream.go
Labels: Tyk Product Development, Sub-task, Review effort [1-5]: 2

#6700 [TT-13508] Downgrade Bento to v1.2.0 and use our own fork to cherry-pick some changes from latest main branch.
  go.mod
  go.sum
  internal/graphql/otel_graphql_engine_detailed_test.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 4

#6701 [TT-13535/TT-13566] make upstream oauth password client secret not required
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: Tyk Product Development, Sub-task, Review effort [1-5]: 2

#6702 Revert "[TT-13422] Do not allow empty string in upstream auth configuration strings"
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: Tyk Product Development, Sub-task, Review effort [1-5]: 2

#6703 Merging to release-5.7: Revert "[TT-13422] Do not allow empty string in upstream auth configuration strings" (#6702)
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: Tyk Product Development, Sub-task, Review effort [1-5]: 2

#6704 Merging to release-5.7.0: Revert "[TT-13422] Do not allow empty string in upstream auth configuration strings" (#6702)
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: Tyk Product Development, Sub-task, Review effort [1-5]: 2

#6706 Merging to release-5.7: [TT-13535/TT-13566] make upstream oauth password client secret not required (#6701)
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: Tyk Product Development, Sub-task, Review effort [1-5]: 1

#6707 Merging to release-5.7.0: [TT-13535/TT-13566] make upstream oauth password client secret not required (#6701)
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: Tyk Product Development, Sub-task, Review effort [1-5]: 1

#6708 [TT-13535/TT-13566] Make upstream oauth flow client secret omitempty
  apidef/api_definitions.go
  apidef/api_definitions_test.go
  apidef/oas/upstream.go
  apidef/schema.go
Labels: Tyk Product Development, Sub-task, Review effort [1-5]: 1

#6710 Merging to release-5.7.0: [TT-13535/TT-13566] Make upstream oauth flow client secret omitempty (#6708)
  apidef/api_definitions.go
  apidef/api_definitions_test.go
  apidef/oas/upstream.go
  apidef/schema.go
Labels: Review effort [1-5]: 1

#6711 [TT-13485] update dependencies with vulnerabilities reported
  go.mod
  go.sum
Labels: Tyk Product Development, Sub-task, Review effort [1-5]: 2

#6712 [TT-13475] update OAS version
  swagger.yml
Labels: Tyk Product Development, Story, Review effort [1-5]: 1

#6715 Merging to release-5.7: [TT-13475] update OAS version (#6712)
  swagger.yml
Labels: Review effort [1-5]: 1

#6716 Merging to release-5.7.0: [TT-13475] update OAS version (#6712)
  swagger.yml
Labels: Review effort [1-5]: 1

#6714 Merging to release-5.7.0: [TT-13485] update dependencies with vulnerabilities reported (#6711)
  go.mod
  go.sum
Labels: Review effort [1-5]: 2

#6713 Merging to release-5.7: [TT-13485] update dependencies with vulnerabilities reported (#6711)
  go.mod
  go.sum
Labels: Review effort [1-5]: 2

#6719 Merging to release-5.7.0: [TT-13535/TT-13566] Ease up required fields in classic API schema (#6717)
  apidef/api_definitions_test.go
  apidef/schema.go
  apidef/schema.json
Labels: Review effort [1-5]: 3

#6718 Merging to release-5.7: [TT-13535/TT-13566] Ease up required fields in classic API schema (#6717)
  apidef/api_definitions_test.go
  apidef/schema.go
  apidef/schema.json
Labels: Review effort [1-5]: 3

#6720 [TT-13607] Only import components/io and components/kafka
  ee/middleware/streams/stream.go
  go.mod
  go.sum
Labels: bug, Tyk Product Development, Review effort [1-5]: 2

#6721 Merging to release-5.7: [TT-13607] Only import components/io and components/kafka (#6720)
  ee/middleware/streams/stream.go
  go.mod
  go.sum
Labels: Review effort [1-5]: 2

#6724 Merging to release-5.7.0: [TT-13507] Fix for custom domains with substring listen path (#6705)
  docker/services/httpbin.yml
  gateway/api_loader.go
  gateway/api_loader_test.go
Labels: Review effort [1-5]: 2

#6725 Merging to release-5.3: Merging to release-5.7.0: [TT-13507] Fix for custom domains with substring listen path (#6705) (#6724)
  docker/services/httpbin.yml
  gateway/api_loader.go
  gateway/api_loader_test.go
Labels: Review effort [1-5]: 2

#6729 [TT-13658] added missing logger from provider initialisation
  ee/middleware/upstreamoauth/middleware.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 1

#6731 Merging to release-5.7.0: [TT-13658] added missing logger from provider initialisation (#6729)
  ee/middleware/upstreamoauth/middleware.go
Labels: Review effort [1-5]: 1

#6730 Merging to release-5.7: [TT-13658] added missing logger from provider initialisation (#6729)
  ee/middleware/upstreamoauth/middleware.go
Labels: Review effort [1-5]: 1
