Repository TykTechnologies/tyk, pull requests merged in 2024-03, with the labels that each got.

#6072 TT-10962
  apidef/adapter/gqlengineadapter/adapter_proxy_only.go
  apidef/adapter/gqlengineadapter/adapter_udg.go
Labels: security, Review effort [1-5]: 2, bug_fix

#6087 [TT-11388]: updated opentelemtry library and added tests for new span keys
  ci/tests/tracing/scenarios/tyk_test-graphql-detailed-tracing-disabled_200.yaml
  ci/tests/tracing/scenarios/tyk_test-graphql-tracing_200.yml
  go.mod
  go.sum
Labels: enhancement, Tests, Review effort [1-5]: 2

#6093 [TT-11377] Adding “node_is_segmented” flag under “node” to complement “tags”
  apidef/rpc.go
  gateway/rpc_storage_handler.go
  gateway/rpc_storage_handler_test.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#6086 [TT-11413] Fix apidef GlobalRateLimit migrations
  apidef/api_definitions.go
  apidef/migration.go
  apidef/migration_test.go
  apidef/oas/oas_test.go
  apidef/oas/upstream.go
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#6103 TT-11288 Revert logger mutex
  gateway/middleware.go
Labels: Review effort [1-5]: 2, bug_fix

#6104 Merging to release-5.2: TT-11288 Revert logger mutex (#6103)
  gateway/middleware.go
Labels: Review effort [1-5]: 2, bug_fix

#6100 [TT-11197] Upgrade google/grpc
  go.mod
  go.sum
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#6098 [TT-11440/TT-11461] Add functionName to replace name in OAS virtual endpoint and endpoint post plugin
  apidef/oas/middleware.go
  apidef/oas/middleware_test.go
  apidef/oas/operation_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: enhancement, Review effort [1-5]: 3

#6113 Merging to release-5.3: [TT-11440/TT-11461] Add functionName to replace name in OAS virtual endpoint and endpoint post plugin (#6098)
  apidef/oas/middleware.go
  apidef/oas/middleware_test.go
  apidef/oas/operation_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: enhancement, Review effort [1-5]: 3

#6097 [TT-11439/TT-11452] fix custom plugins contract
  apidef/oas/middleware.go
  apidef/oas/middleware_test.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#6112 [TT-11295] Update graphql-go-tools dependency
  go.mod
  go.sum
Labels: enhancement, Review effort [1-5]: 1

#6088 [TT-11389]: moved graphql span attributes
  .taskfiles/opentelemetry.yml
  Makefile
  ci/tests/tracing/scenarios/tyk_test-graphql-detailed-tracing-disabled_400.yaml
  ci/tests/tracing/scenarios/tyk_test-graphql-tracing_200.yml
  ci/tests/tracing/scenarios/tyk_test-graphql-tracing_400.yml
  internal/graphql/otel_graphql_engine_basic.go
  internal/graphql/otel_graphql_engine_detailed.go
Labels: enhancement, Review effort [1-5]: 2

#6096 TT-11443 Shim to keep compatibility in goplugins importing tyk redis
  storage/connection_handler_test.go
  storage/redis_cluster.go
  storage/redis_cluster_test.go
  storage/redis_shim.go
  storage/redis_shim_test.go
Labels: enhancement, Review effort [1-5]: 1

#6117 [TT-11452] remove unused migrate func
  apidef/oas/middleware.go
Labels: enhancement, Review effort [1-5]: 1

#6121 Merging to release-5.3: TT-11443 Shim to keep compatibility in goplugins importing tyk redis (#6096)
  storage/connection_handler_test.go
  storage/redis_cluster.go
  storage/redis_cluster_test.go
  storage/redis_shim.go
  storage/redis_shim_test.go
Labels: enhancement, Review effort [1-5]: 3

#6120 TT-11485, fix for global rate limit disabled flag not working
  gateway/mw_api_rate_limit.go
  gateway/mw_api_rate_limit_test.go
Labels: Review effort [1-5]: 1, Bug fix

#6128 Merging to release-5.3.0: TT-11485, fix for global rate limit disabled flag not working (#6120)
  gateway/mw_api_rate_limit.go
  gateway/mw_api_rate_limit_test.go
Labels: Tests, Review effort [1-5]: 2, Bug fix

#6129 Merging to release-5.3: [TT-11389]: moved graphql span attributes (#6088)
  .taskfiles/opentelemetry.yml
  Makefile
  ci/tests/tracing/scenarios/tyk_test-graphql-detailed-tracing-disabled_400.yaml
  ci/tests/tracing/scenarios/tyk_test-graphql-tracing_200.yml
  ci/tests/tracing/scenarios/tyk_test-graphql-tracing_400.yml
  internal/graphql/otel_graphql_engine_basic.go
  internal/graphql/otel_graphql_engine_detailed.go
Labels: enhancement, Tests, Review effort [1-5]: 3

#6130 [SYSE-332] Fail tests reliably
  .github/workflows/pac.yml
  .github/workflows/release.yml
  ci/Dockerfile.std
  ci/bin/pc.sh
  ci/bin/unlock-agent.sh
  ci/goreleaser/goreleaser.yml
  ci/install/before_install.sh
  ci/install/post_install.sh
  ci/install/post_remove.sh
  ci/install/post_trans.sh
  repo-policy/historical-branches.auto.tfvars
  repo-policy/main.tf
  repo-policy/modules/github-repos/repo.tf
  repo-policy/modules/github-repos/variables.tf
Labels: enhancement, Review effort [1-5]: 2, Documentation

#6136 Merging to release-5.3: [TT-11197] Bump github.com/go-jose/go-jose/v3 from 3.0.1 to 3.0.3 (#6124)
  go.mod
  go.sum
Labels: enhancement, dependencies, Review effort [1-5]: 2

#6138 [TT-11549] Auto generated from templates by gromit
  .github/workflows/release.yml
  ci/Dockerfile.std
  ci/bin/pc.sh
  ci/bin/unlock-agent.sh
  ci/goreleaser/goreleaser.yml
  ci/install/before_install.sh
  ci/install/post_install.sh
  ci/install/post_remove.sh
  ci/install/post_trans.sh
  ci/tests/python-plugins/docker-compose.yml
  ci/tests/python-plugins/extend-python/Dockerfile
  ci/tests/python-plugins/extend-python/README.md
Labels: enhancement, Review effort [1-5]: 2

#6133 [TT-10856/TT-11593]fix quota limits not working with url rewrite to self
  gateway/middleware.go
  gateway/middleware_test.go
  gateway/reverse_proxy_test.go
  gateway/session_manager.go
Labels: Tests, Review effort [1-5]: 3, bug_fix

#6143 Merging to release-5.3: [TT-10856/TT-11593]fix quota limits not working with url rewrite to self (#6133)
  gateway/middleware.go
  gateway/middleware_test.go
  gateway/reverse_proxy_test.go
  gateway/session_manager.go
Labels: Tests, Review effort [1-5]: 4, bug_fix

#6150 [TT-11197]update hashicorp vault
  go.mod
  go.sum
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#6166 [TT-10909]: fix issue with missing upstream headers in graphql proxy only
  ci/tests/tracing/scenarios/tyk_test-graphql-tracing-invalid_404.yml
  gateway/handler_success_test.go
  gateway/reverse_proxy_test.go
  internal/graphengine/context.go
  internal/graphengine/engine_v2.go
  internal/graphengine/graphql_go_tools_v1.go
  internal/graphengine/transport.go
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#6174 [TT-11683]: fixed header forwarding
  ci/tests/tracing/scenarios/tyk_test-graphql-tracing-invalid_404.yml
  gateway/mw_graphql_transport.go
  gateway/mw_graphql_transport_test.go
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#6181 [TT-11684] OAS-to-UDG converter - import paths & cleanup
  apidef/adapter/asyncapi.go
  apidef/adapter/openapi.go
  go.mod
  go.sum
Labels: enhancement, dependencies, Review effort [1-5]: 2

#6182 [TT-11735] Exclude testdata from sonarcloud
  .github/workflows/ci-tests.yml
Labels: enhancement, Review effort [1-5]: 1

#6180 [TT-10104] JS middleware + ignore auth test and fix for panic
  gateway/mw_js_plugin.go
  tests/regression/.gitignore
  tests/regression/README.md
  tests/regression/Taskfile.yml
  tests/regression/issue_10104_test.go
  tests/regression/regression_test.go
  tests/regression/testdata/issue-10104-apidef.json
  tests/regression/testdata/issue-10104-script.js
Labels: Tests, Review effort [1-5]: 2, bug_fix

#6035 Update README.md
  README.md
Labels: enhancement, Review effort [1-5]: 1, Documentation

#6191 [TT-11746] Add linter for regression test names
  docker/services/Taskfile.yml
  docker/services/docker-compose.yml
  docker/services/redis.yml
  tests/regression/Taskfile.yml
Labels: enhancement, Tests, Review effort [1-5]: 2

#6193 Merging to release-5.3: [TT-11746] Add linter for regression test names (#6191)
  docker/services/Taskfile.yml
  docker/services/docker-compose.yml
  docker/services/redis.yml
  tests/regression/Taskfile.yml
Labels: enhancement, Tests, Review effort [1-5]: 2

#6190 [TT-11585] Process DeleteAPICache event
  gateway/api.go
  gateway/delete_api_cache.go
  gateway/redis_signals.go
  gateway/rpc_storage_handler.go
  tests/regression/issue_11585_test.go
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#6194 Merging to release-5.3: [TT-11585] Process DeleteAPICache event (#6190)
  gateway/api.go
  gateway/delete_api_cache.go
  gateway/redis_signals.go
  gateway/rpc_storage_handler.go
  tests/regression/issue_11585_test.go
Labels: enhancement, Review effort [1-5]: 3, bug_fix
