Repository TykTechnologies/tyk, pull requests merged in 2024-04, with the labels that each got.

#6199 [TT-10856/TT-11778] fix quota limit remaining header value when key is created from policy and API is looped
  gateway/middleware_test.go
  gateway/mw_auth_key.go
  gateway/reverse_proxy_test.go
Labels: Review effort [1-5]: 4, bug_fix

#6200 Merging to release-5.3: [TT-10856/TT-11778] fix quota limit remaining header value when key is created from policy and API is looped (#6199)
  gateway/middleware_test.go
  gateway/mw_auth_key.go
  gateway/reverse_proxy_test.go
Labels: Bug fix, Review effort [1-5]: 4

#6207 [SYSE-336 master] Followup from March template application
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/release.yml
  ci/Dockerfile.std
  ci/bin/pc.sh
  ci/bin/unlock-agent.sh
  ci/goreleaser/goreleaser.yml
  ci/install/before_install.sh
  ci/install/post_install.sh
  ci/install/post_remove.sh
  ci/install/post_trans.sh
Labels: enhancement, Review effort [1-5]: 2

#6165 TT-7560, fixed issue with bundles loading with bad sign/checksum
  .github/workflows/release.yml
  coprocess/python/coprocess_id_extractor_python_test.go
  coprocess/python/coprocess_python_test.go
  gateway/coprocess_bundle.go
  gateway/coprocess_bundle_test.go
  gateway/mw_js_plugin_test.go
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#6213 [SYSE-353 master] Fix tyk-ci fetch mechanism
  .github/workflows/release.yml
Labels: Review effort [1-5]: 2, bug_fix

#6211 [TT-7560] skip loading API when custom middleware bundle fetch fails
  gateway/api_definition.go
  gateway/coprocess_bundle_test.go
  gateway/coprocess_id_extractor_test.go
  gateway/gateway_test.go
  gateway/testutil.go
  gateway/tracing.go
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#6217 Merging to release-5.3: [TT-7560] skip loading API when custom middleware bundle fetch fails (#6211)
  gateway/api_definition.go
  gateway/coprocess_bundle_test.go
  gateway/coprocess_id_extractor_test.go
  gateway/gateway_test.go
  gateway/testutil.go
  gateway/tracing.go
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#6215 TT-11748 dont attempt to remove ApiCacheDeletion key from redis
  gateway/rpc_storage_handler.go
Labels: Review effort [1-5]: 1, bug_fix

#6234 [TT-11925] Reset plugin compiler build env to match gateway build env
  .github/workflows/plugin-compiler-build.yml
  ci/images/plugin-compiler/Dockerfile
  ci/images/plugin-compiler/Taskfile.yml
Labels: Review effort [1-5]: 1, bug_fix

#6238 Merging to release-5.3: [TT-11925] Reset plugin compiler build env to match gateway build env (#6234)
  .github/workflows/plugin-compiler-build.yml
  ci/images/plugin-compiler/Dockerfile
  ci/images/plugin-compiler/Taskfile.yml
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#6237 Merging to release-5.3.1: [TT-11925] Reset plugin compiler build env to match gateway build env (#6234)
  .github/workflows/plugin-compiler-build.yml
  ci/images/plugin-compiler/Dockerfile
  ci/images/plugin-compiler/Taskfile.yml
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#6221 [TT-11655] Graphql APIs are unable to handle OPTIONS requests
  internal/graphengine/consts.go
  internal/graphengine/engine_v1.go
  internal/graphengine/engine_v1_test.go
  internal/graphengine/engine_v2.go
  internal/graphengine/engine_v2_test.go
  internal/graphengine/graphql_go_tools_v1.go
  internal/graphengine/graphql_go_tools_v1_test.go
Labels: Review effort [1-5]: 2, Bug fix

#6249 [SYSE-358 release-5.3] April template application
  .github/workflows/pac.yml
  .github/workflows/release.yml
  ci/Dockerfile.std
  ci/bin/pc.sh
  ci/bin/unlock-agent.sh
  ci/goreleaser/goreleaser.yml
  ci/install/before_install.sh
  ci/install/post_install.sh
  ci/install/post_remove.sh
  ci/install/post_trans.sh
  repo-policy/historical-branches.auto.tfvars
  repo-policy/main.tf
  repo-policy/modules/github-repos/repo.tf
  repo-policy/modules/github-repos/variables.tf
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#6248 [SYSE-358 master] April template application
  .github/workflows/release.yml
  ci/Dockerfile.std
Labels: enhancement, Review effort [1-5]: 4, bug_fix
