Repository TykTechnologies/tyk, pull requests merged in 2024-10, with the labels that each got.

#6581 [SYSE-399 release-5.6] distroless missing from 5.5 and 5.6
  .github/workflows/release.yml
Labels: enhancement, Tests, Review effort [1-5]: 3

#6594 [SYSE-399 release-5.5] distroless missing from 5.5 and 5.6
  .github/workflows/release.yml
Labels: enhancement, Review effort [1-5]: 4, configuration changes

#6583 [SYSE-394 master] Fix test code base for Tyk-Analytics PRs
  .github/workflows/release.yml
Labels: enhancement, Tests, Review effort [1-5]: 4

#6610 [TT-13088] Fixed godoc for path prefix and sufix configs
  config/config.go
Labels: Tyk Product Development, Task

#6614 Merging to release-5.3: [TT-13088] Fixed godoc for path prefix and sufix configs (#6610)
  config/config.go
Labels: Tyk Product Development, Task

#6596 [TT-13186/TT-13199] implement upstream basic authentication
  apidef/api_definitions.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/upstream.go
  apidef/schema.go
  ctx/ctx.go
  gateway/api_loader.go
  gateway/mw_upstream_basic_auth.go
  gateway/mw_upstream_basic_auth_test.go
  gateway/reverse_proxy.go
  internal/httputil/context.go
  internal/httputil/context_test.go
  internal/httputil/headers.go
  internal/model/upstream_auth.go
  test/http.go
Labels: enhancement, Tyk Product Development, Sub-task, Tests, Review effort [1-5]: 4

#6611 [TT-13243] Test/ci improvements
  .github/workflows/ci-tests.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/plugin-compiler-build.yml
  .golangci.yml
Labels: Tyk Product Development, Task

#6601 [TT-13139] Request times out in some cases when sending input via http inputs
  gateway/mw_streaming.go
  gateway/mw_streaming_test.go
Labels: bug, enhancement, Tyk Product Development, Tests, Review effort [1-5]: 4

#6613 Merging to release-5.6.0: [TT-13088] Fixed godoc for path prefix and sufix configs (#6610)
  config/config.go
Labels: Tyk Product Development, Task

#6612 Merging to release-5.6: [TT-13088] Fixed godoc for path prefix and sufix configs (#6610)
  config/config.go
Labels: Tyk Product Development, Task

#6608 [TT-13238] Clean up RPC data model
  .github/workflows/ci-tests.yml
  apidef/rpc.go
  gateway/health_check.go
  gateway/rpc_storage_handler.go
  gateway/rpc_storage_handler_test.go
  gateway/rpc_test.go
  internal/model/host_details.go
  internal/model/rpc.go
  rpc/rpc_client.go
  rpc/rpc_client_test.go
Labels: enhancement, Tyk Product Development, Task, Bug fix, Review effort [1-5]: 3

#6609 [TT-13242] Moved/Cleaned up nestedApiDefinition to model.MergedAPI
  gateway/api_definition.go
  gateway/api_definition_test.go
  gateway/coprocess_id_extractor_test.go
  gateway/policy_test.go
  gateway/testutil.go
  gateway/tracing.go
  internal/model/merged_apis.go
Labels: enhancement

#6620 [TT-13258] exp/workflow-lint: Update to latest known actions
  .github/workflows/ci-tests.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/plugin-compiler-build.yml
Labels: Tyk Product Development, Story

#6624 [TT-13266] Fix python tests
  .github/workflows/ci-tests.yml
  dlpython/main.go
  dlpython/main_test.go
  dlpython/version.go
  dlpython/version_test.go
Labels: Tyk Product Development, Task, Review effort [1-5]: 1, bug_fix, configuration changes

#6623 [TT-13262] Fix/delete build cache for plugin compiler
  .github/workflows/ci-tests.yml
  .github/workflows/plugin-compiler-build.yml
  ci/images/plugin-compiler/Dockerfile
  ci/images/plugin-compiler/Taskfile.yml
Labels: enhancement, Tyk Product Development, Task, Review effort [1-5]: 2, configuration changes

#6618 [TT-8004/TT-13092]enable validate request middleware during OAS import when parameters are specified on endpoint groups
  apidef/oas/default.go
  apidef/oas/default_test.go
  apidef/oas/operation.go
Labels: Tyk Product Development, Sub-task

#6631 [TT-13186/TT-13199] replace auth header instead of adding auth header
  gateway/mw_upstream_basic_auth.go
Labels: enhancement, Tyk Product Development, Sub-task, Review effort [1-5]: 2

#6634 [TT-13280] Adjust golangci-lint to raise up errors in PRs directly
  .github/workflows/ci-tests.yml
Labels: enhancement, Tyk Product Development, Task, Review effort [1-5]: 2, configuration changes

#6629 TT-13130 updated version of gorpc library and prevent panic on reconnect edge
  go.mod
  go.sum
  rpc/rpc_client.go
Labels: bug, Tyk Product Development, Bug fix, Review effort [1-5]: 3

#6637 Merging to release-5.3: TT-13130 updated version of gorpc library and prevent panic on start edge (#6629)
  go.mod
  go.sum
  rpc/rpc_client.go
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#6633 [TT-13184] Implement OAuth 2.0 Client Credentials Flow for GW authentication with upstream
  apidef/api_definitions.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/upstream.go
  apidef/schema.go
  gateway/api_loader.go
  gateway/event_system.go
  gateway/middleware.go
  gateway/mw_oauth2_auth.go
  gateway/mw_oauth2_auth_test.go
  gateway/rpc_backup_handlers.go
  gateway/server.go
  go.mod
Labels: enhancement, Tests, Review effort [1-5]: 4

#6638 Merging to release-5.6: TT-13130 updated version of gorpc library and prevent panic on start edge (#6629)
  go.mod
  go.sum
  rpc/rpc_client.go
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#6635 [TT-12897/TT-13284] Add additional partitioned test case, fix ordering issue
  internal/policy/apply.go
  internal/policy/apply_test.go
Labels: bug, Tyk Product Development, Tests, Bug fix, Review effort [1-5]: 3

#6639 Merging to release-5.3: [TT-12897/TT-13284] Add additional partitioned test case, fix ordering issue (#6635)
  gateway/middleware.go
  tests/policy/apply_acl_test.go
  tests/policy/shim.go
  user/custom_policies.go
Labels: Tests, Bug fix, Review effort [1-5]: 3

#6640 [TT-12814] Make schema more flexible, don't enforce additionalProperties: false
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: bug, enhancement, Tyk Product Development, Review effort [1-5]: 3

#6645 Merging to release-5.3: TT-13130 update gorpc version (#6644)
  go.mod
  go.sum
  rpc/rpc_client.go
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#6646 Merging to release-5.6.1: TT-13130 update gorpc version (#6644)
  go.mod
  go.sum
  rpc/rpc_client.go
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#6647 Merging to release-5.3.7: TT-13130 update gorpc version (#6644)
  go.mod
  go.sum
  rpc/rpc_client.go
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#6651 [TT-12990] fix upstream endpoint RL not considering endpoint method
  gateway/mw_api_rate_limit.go
  tests/rate/per_api_limit_test.go
Labels: bug, Tyk Product Development, Tests, Bug fix, Review effort [1-5]: 3

#6648 Merging to release-5.6: TT-13130 update gorpc version (#6644)
  go.mod
  go.sum
  rpc/rpc_client.go
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#6593 TT-13269 - Refactor/streams
  .github/workflows/plugin-compiler-build.yml
  .github/workflows/release.yml
  LICENSE.md
  README.md
  ci/Dockerfile.distroless
  ci/goreleaser/goreleaser.yml
  ci/images/plugin-compiler/Dockerfile
  ci/images/plugin-compiler/data/build.sh
  ee/EULA.pdf
  ee/LICENSE-EE.md
  ee/middleware/streams/manager.go
  ee/middleware/streams/middleware.go
  ee/middleware/streams/model.go
  ee/middleware/streams/stream.go
  ee/middleware/streams/stream_test.go
  ee/middleware/streams/util.go
  gateway/api_loader.go
  gateway/gateway.go
  gateway/middleware.go
  gateway/middleware_wrap.go
  gateway/mw_auth_key.go
  gateway/mw_graphql.go
  gateway/mw_modify_headers.go
  gateway/mw_persist_graphql_operation.go
  gateway/mw_rate_limiting.go
  gateway/mw_streaming.go
  gateway/mw_streaming_ee.go
  gateway/mw_streaming_test.go
  gateway/mw_transform.go
  gateway/mw_url_rewrite.go
  gateway/res_handler_header_injector.go
  gateway/rpc_storage_handler.go
  gateway/rpc_storage_handler_test.go
  gateway/rpc_test.go
  go.mod
  internal/middleware/const.go
  internal/model/interfaces.go
  internal/policy/apply.go
Labels: enhancement, Tests, Review effort [1-5]: 4

#6661 update code of usage of gorpc waitgroup
  rpc/rpc_client.go
Labels: bug, Tyk Product Development

#6654 [TT-12702] revert wrappedServeHTTP to use recordDetail
  .github/workflows/release.yml
  .gitignore
  gateway/handler_success.go
  gateway/handler_success_test.go
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 2, Bug fix

#6657 [TT-11426/TT-13322] Add deprecation notice for external OAuth middleware
  .github/workflows/release.yml
  apidef/api_definitions.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/security.go
  gateway/mw_external_oauth.go
Labels: Tyk Product Development, Sub-task, Review effort [1-5]: 2

#6649 [TT-13185] Implement Password Flow OAuth
  apidef/api_definitions.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/upstream.go
  apidef/schema.go
  gateway/mw_oauth2_auth.go
  gateway/mw_oauth2_auth_test.go
  gateway/rpc_backup_handlers.go
Labels: enhancement, Tests, Review effort [1-5]: 4

#6664 [TT-13381] Linters should only work for PRs
  .github/workflows/lint.yml
Labels: Tyk Product Development, Task, Review effort [1-5]: 1

#6666 Merging to release-5.0.15: [TT-13110] remove trimpath from 5-lts build (#6546)
  ci/goreleaser/goreleaser.yml
Labels: bug, Tyk Product Development

#6667 Merging to release-5.3: [TT-12417] Do not delete keys on synchronization (#6642)
  gateway/rpc_storage_handler.go
  rpc/synchronization_forcer.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 3

#6668 [TT-13185] reorganize contract in upstream oauth
  apidef/api_definitions.go
  apidef/oas/linter_test.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/upstream.go
  apidef/schema.go
  gateway/mw_oauth2_auth.go
  gateway/mw_oauth2_auth_test.go
Labels: Tyk Product Development, Story

#6660 [TT-13271] custom oauth response fields
  apidef/api_definitions.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/upstream.go
  apidef/schema.go
  gateway/api_loader.go
  gateway/mw_oauth2_auth.go
  gateway/mw_oauth2_auth_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 3

#6669 [TT-13359] move upstream basic auth to ee package
  apidef/api_definitions.go
  apidef/oas/upstream.go
  ee/middleware/upstreambasicauth/middleware.go
  ee/middleware/upstreambasicauth/model.go
  ee/middleware/upstreambasicauth/provider.go
  gateway/api_loader.go
  gateway/mw_upstream_basic_auth.go
  gateway/mw_upstream_basic_auth_ee.go
  gateway/mw_upstream_basic_auth_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 3

#6676 [TT-13185] upstream oauth allowed_authorize_types not being filled on API creation
  apidef/oas/oas_test.go
  apidef/oas/upstream.go
  gateway/mw_oauth2_auth.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 2

#6681 TT-13185, fixed lines lost in merge conflicts
  apidef/oas/oas_test.go
  apidef/oas/upstream.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 3

#6680 [TT-13375/TT-13422] Add validation rules for Upstream auth
  apidef/api_definitions.go
  apidef/validator.go
  apidef/validator_test.go
  gateway/mw_oauth2_auth.go
  gateway/mw_oauth2_auth_test.go
Labels: Tyk Product Development, Sub-task, Review effort [1-5]: 3

#6682 [TT-13008]: modified default streams logger
  ee/middleware/streams/manager.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 2

#6685 [TT-13185] fix missing extracts
  apidef/api_definitions.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/upstream.go
  apidef/schema.go
  gateway/mw_oauth2_auth_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 3

#6686 [TT-11426/TT-13322]add deprecation notice for oidc middleware
  apidef/api_definitions.go
  apidef/oas/authentication.go
  apidef/oas/schema/x-tyk-api-gateway.json
  gateway/mw_openid.go
Labels: Tyk Product Development, Sub-task, Review effort [1-5]: 2

#6656 [TT-13201] Streams Definition Validator
  apidef/api_definitions.go
  apidef/oas/oas.go
  apidef/oas/tyk_streaming_extension.go
  apidef/streams/bento/schema/bento-v1.2.0-supported-schema.json
  apidef/streams/bento/validator.go
  apidef/streams/bento/validator_test.go
  apidef/streams/schema/3.0.json
  apidef/streams/schema/x-tyk-api-gateway.json
  apidef/streams/schema/x-tyk-streaming.json
  apidef/streams/testdata/empty-x-tyk-ext-oas-template.json
  apidef/streams/testdata/non-empty-x-tyk-ext-oas-template.json
  apidef/streams/validator.go
  apidef/streams/validator_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6688 [TT-11426/TT-13322] Add deprecation notice for external OAuth middleware(#6657)
  apidef/api_definitions.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/security.go
  gateway/mw_external_oauth.go
Labels: Review effort [1-5]: 2

#6687 Merging to release-5.3: [TT-11426/TT-13322]add deprecation notice for oidc middleware (#6686)
  apidef/api_definitions.go
  apidef/oas/authentication.go
  apidef/oas/schema/x-tyk-api-gateway.json
  gateway/mw_openid.go
Labels: Review effort [1-5]: 2
