Repository TykTechnologies/tyk, pull requests merged in 2024-08, with the labels that each got.

#6444 Merging to release-5.3: [TT-12762]respect response plugins contract over responsePlugin.plugins (#6441)
  apidef/oas/middleware.go
  apidef/oas/middleware_test.go
Labels: Tests, Review effort [1-5]: 2, Bug fix

#6455 [TT-12816] Fix/distroless python release tests
  ci/tests/python-plugins/docker-compose.yml
  ci/tests/python-plugins/extend-python/Dockerfile
  ci/tests/python-plugins/src/Dockerfile
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#6458 Merging to release-5.3: [TT-12816] Fix/distroless python release tests (#6455)
  ci/tests/python-plugins/docker-compose.yml
  ci/tests/python-plugins/extend-python/Dockerfile
  ci/tests/python-plugins/src/Dockerfile
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#6454 [DX-1599] Update ports_whitelist config documentation
  config/config.go
Labels: Review effort [1-5]: 2, Documentation

#6460 Merging to release-5.5: [DX-1599] Update ports_whitelist config documentation (#6454)
  config/config.go
Labels: Review effort [1-5]: 1, Documentation

#6427 [TT-11726]: This optimizes the deletion of keys using a single command
  gateway/api_test.go
  gateway/auth_manager.go
  gateway/auth_manager_test.go
  gateway/ldap_auth_handler.go
  gateway/rpc_storage_handler.go
  storage/dummy.go
  storage/mdcb_storage.go
  storage/redis_cluster.go
  storage/redis_cluster_test.go
  storage/storage.go
Labels: enhancement, Review effort [1-5]: 2

#6418 [SYSE-370 master] June template application
  .github/workflows/release.yml
  ci/goreleaser/goreleaser.yml
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#6466 [SYSE-370 release-5.5] June template application
  .github/workflows/release.yml
  ci/goreleaser/goreleaser.yml
Labels: enhancement, Review effort [1-5]: 4, configuration changes

#6419 [SYSE-370 release-5.3] June template application
  .github/workflows/release.yml
  ci/Dockerfile.distroless
  ci/goreleaser/goreleaser.yml
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#6462 [TT-12566/TT-12851] Add client endpoint rate limiter
  .taskfiles/test.yml
  gateway/mw_api_rate_limit_test.go
  gateway/mw_jwt_test.go
  gateway/mw_rate_limiting_test.go
  gateway/policy.go
  gateway/policy_test.go
  gateway/session_manager.go
  gateway/session_manager_test.go
  internal/policy/apply_test.go
  swagger.yml
  test/http.go
  tests/rate/endpoint_rate_limit_test.go
  user/policy.go
  user/session.go
  user/session_test.go
Labels: enhancement, Tests, Review effort [1-5]: 4

#6465 [TT-12862] refactor apply policy
  gateway/policy_test.go
  gateway/testdata/policies.json
  internal/policy/apply.go
  user/policy.go
Labels: enhancement, Tests, Review effort [1-5]: 4

#6437 [TT-12550] policy key path permissions problem
  gateway/api_definition.go
  gateway/api_definition_test.go
  gateway/handler_error.go
  gateway/mw_granular_access.go
  gateway/mw_granular_access_test.go
  gateway/mw_request_signing.go
  internal/httputil/Taskfile.yml
  internal/httputil/connection_watcher.go
  internal/httputil/mux.go
  internal/httputil/mux_test.go
  internal/httputil/response.go
  internal/httputil/streaming_test.go
  internal/maps/strings.go
Labels: enhancement, Tests, Bug fix, Review effort [1-5]: 3

#6468 [TT-12886] apply per endpoint rate limits
  gateway/policy_test.go
  gateway/testdata/policies.json
  internal/policy/apply.go
  user/session.go
  user/session_test.go
Labels: enhancement, Tests, Review effort [1-5]: 4

#6470 [TT-12892] use same url matching logic in endpoint rate limiting as of allowed urls
  gateway/mw_granular_access.go
  gateway/session_manager.go
  internal/httputil/mux.go
  internal/httputil/mux_test.go
  user/session.go
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#6472 [TT-12566/TT-12927] fix merging rate limits
  gateway/policy_test.go
  gateway/testdata/policies.json
  internal/policy/apply.go
Labels: Bug fix, Review effort [1-5]: 3

#6469 Merging to release-5.3: [TT-12550] policy key path permissions problem (#6437)
  gateway/api_definition.go
  gateway/api_definition_test.go
  gateway/handler_error.go
  gateway/mw_granular_access.go
  gateway/mw_granular_access_test.go
  gateway/mw_request_signing.go
  internal/httputil/Taskfile.yml
  internal/httputil/connection_watcher.go
  internal/httputil/mux.go
  internal/httputil/mux_test.go
  internal/httputil/response.go
  internal/httputil/streaming_test.go
  internal/maps/strings.go
Labels: enhancement, Tests, Bug fix, Review effort [1-5]: 3

#6169 [TT-11672] Update description of CertificatesConfig.Upstream
  config/config.go
Labels: Review effort [1-5]: 1, Documentation
