Repository TykTechnologies/tyk, pull requests merged in 2024-01, with the labels that each got.

#5970 [TT-11071] Update graphql-go-tools
  go.mod
  go.sum
Labels: Review effort [1-5]: 1

#5973 [TT-11057] Enable context vars for OAS APIs always
  apidef/oas/oas_test.go
  apidef/oas/root.go
Labels: enhancement, Review effort [1-5]: 2

#5972 [TT-11104] Add missing test for endpoint level request size limit
  gateway/mw_request_size_limit_test.go
Labels: Review effort [1-5]: 1, Tests

#5974 [TT-11105] Add disabled flag for endpoint level request size limit
  apidef/api_definitions.go
  apidef/oas/oas_test.go
  gateway/api_definition.go
  gateway/mw_request_size_limit_test.go
Labels: enhancement, Review effort [1-5]: 2

#5982 [TT-11106] Add request size limit OAS conversion
  apidef/api_definitions.go
  apidef/oas/middleware.go
  apidef/oas/oas_test.go
  apidef/oas/operation.go
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: enhancement, Review effort [1-5]: 3

#5979 [TT-10858/TT-11116]implement OAS per api rate limit
  apidef/oas/linter_test.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/upstream.go
  apidef/oas/upstream_test.go
Labels: enhancement, Review effort [1-5]: 3

#5986 [TT-11043] Allow empty x-tyk ext to be valid in OAS template
  apidef/oas/testdata/empty-x-tyk-ext-oas-template.json
  apidef/oas/testdata/non-empty-x-tyk-ext-oas-template.json
  apidef/oas/validator.go
  apidef/oas/validator_test.go
Labels: enhancement, Review effort [1-5]: 2

#5977 [TT-10992/TT-11108]Remove slug from oas.server
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/server.go
  apidef/oas/testdata/urlRewrite.json
Labels: enhancement, Review effort [1-5]: 2

#5980 [TT-10438] add date, date-time validation hooks for validate request on kin-openapi3
  gateway/mw_oas_validate_request.go
  gateway/mw_oas_validate_request_test.go
Labels: Review effort [1-5]: 2, Bug fix

#5989 [TT-10778/TT-11129] Configure consule scheme
  storage/kv/consul.go
Labels: Review effort [1-5]: 1, Bug fix

#5988 [TT-11106] Set minimum value 0 in request size limit schema
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: Review effort [1-5]: 1, Bug fix

#5994 [TT-10778/TT-11131] Implement kv replace for env
  gateway/api_definition.go
  gateway/api_definition_test.go
Labels: enhancement, Review effort [1-5]: 2

#5991 [TT-11135] add pattern and rewriteTo as required fields for url rewrite
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: Review effort [1-5]: 1, Bug fix

#5993 [TT-10894], disable strict oas validation on examples and schema
  apidef/oas/oas.go
  apidef/oas/oas_test.go
  cli/linter/schema.json
  config/config.go
  gateway/api.go
  gateway/api_definition.go
  gateway/server.go
Labels: enhancement, Review effort [1-5]: 3

#6001 [TT-11150]retain `slug` in tyk schema
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: Review effort [1-5]: 1, Bug fix

#6005 TT-11063 Corrected typos in godocs
  config/config.go
Labels: Review effort [1-5]: 1, Documentation

#5996 [TT-10778/ TT-11132] Implement kv replace for consul
  gateway/api_definition.go
  storage/kv/consul.go
Labels: enhancement, Review effort [1-5]: 2

#6004 [TT-10858/TT-11156] OAS migration: disable rate limit when per and rate are 0
  apidef/migration.go
  apidef/migration_test.go
Labels: Review effort [1-5]: 2, Bug fix
