Repository TykTechnologies/tyk, pull requests merged in 2025-07, with the labels that each got.

#7173 [TT-14990] Update GetCiphers to restore support for legacy TLS cipher suites
  internal/crypto/ciphers.go
  internal/crypto/ciphers_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7183 Merging to release-5.9: [TT-14990] Update GetCiphers to restore support for legacy TLS cipher suites (#7173)
  internal/crypto/ciphers.go
  internal/crypto/ciphers_test.go
Labels: bug, Tyk Product Development

#7163 [TT-9234] fixes for graceful shutdown regression bugs
  config/config.go
  gateway/server.go
Labels: Tyk Product Development, Story, Review effort 2/5

#7202 [TT-9234] regression fixes with incorrect behaviour
  gateway/server.go
Labels: Tyk Product Development, Story, Review effort 3/5

#7207 [TT-9234] regression fixes
  gateway/server.go
  gateway/server_test.go
  tcp/tcp.go
  tcp/tcp_test.go
Labels: Tyk Product Development, Story

#7225 TT-14838 Addressed comments on GW docs improvements
  apidef/oas/middleware.go
  config/config.go
Labels: Tyk Product Development, Story, Review effort 1/5

#7230 [TT-15251] GW prints body decompression error when when you enable analytics
  gateway/handler_success.go
  gateway/handler_success_test.go
  gateway/testutil.go
Labels: bug, Tyk Product Development, Review effort 3/5

#7208 [TT-14914] No response middleware information in Tyk OAS API Debugger
  gateway/middleware.go
  gateway/model_apispec.go
  gateway/mw_mock_response.go
  gateway/mw_redis_cache.go
  gateway/mw_virtual_endpoint.go
  gateway/reverse_proxy.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7246 [TT-15321]: added documentation to dev docs for OAS only feature and added helper method
  docs/dev/oas_only_feature_development.md
  gateway/model_apispec.go
Labels: Tyk Product Development, Sub-task, Review effort 2/5

#7233 [TT-11244] Custom domain regex causing problems with servers
  apidef/oas/oas.go
  apidef/oas/oas_test.go
  gateway/api.go
  internal/oasutil/servers.go
  internal/oasutil/servers_test.go
Labels: bug, Tyk Product Development, Review effort 4/5

#7244 [TT-7523] [OAS Versioning] Gateway CE allows to create version without `new_version_name`
  gateway/api.go
  gateway/api_test.go
  lib/apidef/version.go
  lib/apidef/version_test.go
Labels: bug, Tyk Product Development, Review effort 4/5

#7256 [TT-14370] [OAS] ReadableDuration converts some values to decimals causing a schema problem
  internal/time/duration.go
  internal/time/duration_test.go
Labels: bug, Tyk Product Development, Review effort 2/5
