Repository TykTechnologies/tyk, pull requests merged in 2025-03, with the labels that each got.

#6913 TT-14244: [release-5.3] Bump go, set godebug for compatibility
  go.mod
Labels: Tyk Product Development, Task, Review effort 2/5

#6917 [TT-14169] Review and address CVEs
  go.mod
  go.sum
Labels: Review effort 3/5

#6918 Merging to release-5.8: [TT-14169] Review and address CVEs (#6917)
  go.mod
  go.sum
Labels: Review effort 3/5

#6922 Merging to release-5.8.0: [TT-14169] Review and address CVEs (#6917)
  go.mod
  go.sum
Labels: Review effort 3/5

#6921 Merging to release-5.8.0: [TT-14170] Config and swagger description updates (#6919)
  apidef/oas/authentication.go
  apidef/oas/middleware.go
  apidef/oas/upstream.go
  config/config.go
  swagger.yml
Labels: Review effort 2/5

#6920 Merging to release-5.8: [TT-14170] Config and swagger description updates (#6919)
  apidef/oas/authentication.go
  apidef/oas/middleware.go
  apidef/oas/upstream.go
  config/config.go
  swagger.yml
Labels: Review effort 2/5

#6916 [TT-14214]: added milisecond duration to readable duration
  apidef/oas/linter_test.go
  apidef/oas/middleware_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/schema/x-tyk-api-gateway.strict.json
  apidef/oas/upstream_test.go
  internal/time/duration.go
  internal/time/duration_test.go
Labels: bug, Tyk Product Development, Review effort 3/5

#6925 [TT-14169] Upgrade github.com/go-jose/go-jose/v3
  go.mod
  go.sum
Labels: Review effort 1/5

#6927 Merging to release-5.8: [TT-14169] Upgrade github.com/go-jose/go-jose/v3 (#6925)
  go.mod
  go.sum
Labels: Review effort 1/5

#6928 Merging to release-5.8.0: [TT-14169] Upgrade github.com/go-jose/go-jose/v3 (#6925)
  go.mod
  go.sum
Labels: Review effort 1/5

#6929 Merging to release-5.8: [TT-14214]: added milisecond duration to readable duration (#6916)
  apidef/oas/linter_test.go
  apidef/oas/middleware_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/schema/x-tyk-api-gateway.strict.json
  apidef/oas/upstream_test.go
  internal/time/duration.go
  internal/time/duration_test.go
Labels: Review effort 3/5

#6924 [TT-12957] fix some issues with uptime_tests migrations to OAS
  apidef/api_definitions.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/schema/x-tyk-api-gateway.strict.json
  apidef/oas/testdata/fixtures/upstream_uptimeTests.yml
  apidef/oas/upstream.go
  apidef/oas/upstream_test.go
  gateway/host_checker_manager.go
  gateway/host_checker_manager_test.go
Labels: Tyk Product Development, Sub-task

#6926 TT-14170 Update missing Tyk OAS API go doc on fields
  apidef/oas/authentication.go
  apidef/oas/event.go
  apidef/oas/middleware.go
  apidef/oas/root.go
  apidef/oas/security.go
  apidef/oas/server.go
  apidef/oas/upstream.go
  apidef/oas/url_rewrite.go
  config/config.go
Labels: Tyk Product Development, Story, Review effort 3/5

#6933 Merging to release-5.8.0: TT-14170 Update missing Tyk OAS API go doc on fields (#6926)
  apidef/oas/authentication.go
  apidef/oas/event.go
  apidef/oas/middleware.go
  apidef/oas/root.go
  apidef/oas/security.go
  apidef/oas/server.go
  apidef/oas/upstream.go
  apidef/oas/url_rewrite.go
  config/config.go
Labels: Review effort 3/5

#6932 Merging to release-5.8: TT-14170 Update missing Tyk OAS API go doc on fields (#6926)
  apidef/oas/authentication.go
  apidef/oas/event.go
  apidef/oas/middleware.go
  apidef/oas/root.go
  apidef/oas/security.go
  apidef/oas/server.go
  apidef/oas/upstream.go
  apidef/oas/url_rewrite.go
  config/config.go
Labels: Review effort 3/5

#6910 TT-14163 when start the rpc set as default in emergency mode
  rpc/rpc_client.go
Labels: bug, Tyk Product Development, Review effort 3/5

#6935 Merging to release-5.8.0: TT-14163 when start the rpc set as default in emergency mode (#6910)
  rpc/rpc_client.go
Labels: Review effort 3/5

#6934 Merging to release-5.8: TT-14163 when start the rpc set as default in emergency mode (#6910)
  rpc/rpc_client.go
Labels: Review effort 3/5

#6923 [TT-7306] Ensure ignoreAuthentication is only enabled in migration scenario
  apidef/oas/operation.go
  apidef/oas/operation_test.go
  apidef/oas/testdata/fixtures/mock_response.yml
Labels: bug, Tyk Product Development, Review effort 2/5

#6942 [SYSE-401 release-5.3] Model builds as a concept
  .github/workflows/release.yml
  ci/Dockerfile.distroless
  ci/Dockerfile.std
  ci/goreleaser/goreleaser.yml
  ci/tests/api-functionality/api_test.sh
Labels: Review effort 4/5

#6937 Merging to release-5.8.0: [TT-7306] Ensure ignoreAuthentication is only enabled in migration scenario (#6923)
  apidef/oas/operation.go
  apidef/oas/operation_test.go
  apidef/oas/testdata/fixtures/mock_response.yml
Labels: Review effort 2/5

#6938 TT-14170 adjusted godoc for gw config
  config/config.go
Labels: Tyk Product Development, Story, Review effort 2/5

#6944 Merging to release-5.8: TT-14170 adjusted godoc for gw config (#6938)
  config/config.go
Labels: Tyk Product Development, Story, Review effort 2/5

#6945 Merging to release-5.8.0: TT-14170 adjusted godoc for gw config (#6938)
  config/config.go
Labels: Tyk Product Development, Story, Review effort 2/5

#6947 [TT-12957] fixed issue when migrating from classic to oas that was leaving a broken url
  apidef/oas/upstream.go
Labels: Tyk Product Development, Sub-task, Review effort 1/5

#6943 [SYSE-401 release-5.8] Model builds as a concept
  .github/workflows/release.yml
  ci/Dockerfile.distroless
  ci/Dockerfile.std
  ci/goreleaser/goreleaser.yml
  ci/tests/api-functionality/api_test.sh
Labels: Review effort 4/5

#6946 [TT-7306] Revert allow list to migrated mock response
  apidef/oas/operation.go
  apidef/oas/testdata/fixtures/mock_response.yml
Labels: bug, Tyk Product Development, Review effort 3/5

#6948 Merging to release-5.8: [TT-7306] Revert allow list to migrated mock response (#6946)
  apidef/oas/operation.go
  apidef/oas/testdata/fixtures/mock_response.yml
Labels: Review effort 3/5

#6949 Merging to release-5.8.0: [TT-7306] Revert allow list to migrated mock response (#6946)
  apidef/oas/operation.go
  apidef/oas/testdata/fixtures/mock_response.yml
Labels: Review effort 3/5

#6931 [TT-14102] fix api level and endpoint level cache migration
  apidef/migration.go
  apidef/migration_test.go
  apidef/oas/middleware.go
  apidef/oas/middleware_test.go
  apidef/oas/testdata/fixtures/cache.yml
Labels: bug, Tyk Product Development, Review effort 2/5

#6950 Merging to release-5.8: [TT-14102] fix api level and endpoint level cache migration (#6931)
  apidef/migration.go
  apidef/migration_test.go
  apidef/oas/middleware.go
  apidef/oas/middleware_test.go
  apidef/oas/testdata/fixtures/cache.yml
Labels: Review effort 2/5

#6951 Merging to release-5.8.0: [TT-14102] fix api level and endpoint level cache migration (#6931)
  apidef/migration.go
  apidef/migration_test.go
  apidef/oas/middleware.go
  apidef/oas/middleware_test.go
  apidef/oas/testdata/fixtures/cache.yml
Labels: Review effort 2/5

#6954 Merging to release-5.8: [TT-7306] [fix] Migrate Mock Response from Classic API Definition to OAS API Definition (#6914)
  apidef/oas/operation.go
  apidef/oas/operation_test.go
  apidef/oas/testdata/fixtures/mock_response.yml
Labels: Review effort 3/5

#6955 Merging to release-5.8.0: [TT-7306] [fix] Migrate Mock Response from Classic API Definition to OAS API Definition (#6914)
  apidef/oas/operation.go
  apidef/oas/operation_test.go
  apidef/oas/testdata/fixtures/mock_response.yml
Labels: Review effort 3/5

#6956 [TT-12957] oas uptime testing migration fails on timeout field
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/schema/x-tyk-api-gateway.strict.json
  apidef/oas/testdata/fixtures/upstream_uptimeTests.yml
  internal/time/duration.go
Labels: Tyk Product Development, Story, Review effort 2/5

#6960 [TT-14276] Gateway panics if Uptime Tests are disabled in config but enabled in API definition
  gateway/host_checker_test.go
  gateway/reverse_proxy.go
Labels: bug, Tyk Product Development, Review effort 2/5

#6963 [TT-14244] Bump go, set godebug for compatibility
  go.mod
Labels: Review effort 2/5

#6964 CI fix for linter failing when PR target branch is not master
  .taskfiles/lint.yml
Labels: Review effort 2/5

#6961 Merging to release-5.8: [TT-14276] Gateway panics if Uptime Tests are disabled in config but enabled in API definition (#6960)
  .taskfiles/lint.yml
  gateway/host_checker_test.go
  gateway/reverse_proxy.go
Labels: bug, Tyk Product Development, Review effort 2/5

#6965 Tt 14350 fix gateway linter using wrong branch causing ci to mailfunction on release p rs
  .taskfiles/lint.yml
Labels: Tyk Product Development, Story, Review effort 2/5

#6968 Merging to release-5.8: Tt 14350 fix gateway linter using wrong branch causing ci to mailfunction on release p rs (#6965)
  .taskfiles/lint.yml
Labels: Review effort 2/5

#6967 [TT-14358] Fix mock response fixtures in 5.8.0 branch
  .taskfiles/lint.yml
  apidef/oas/testdata/fixtures/mock_response.yml
Labels: Review effort 2/5

#6969 Merging to release-5.8.0: Tt 14350 fix gateway linter using wrong branch causing ci to mailfunction on release p rs (#6965)
  .taskfiles/lint.yml
Labels: Review effort 2/5

#6958 Merging to release-5.8: [TT-12957] oas uptime testing migration fails on timeout field (#6956)
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/schema/x-tyk-api-gateway.strict.json
  apidef/oas/testdata/fixtures/upstream_uptimeTests.yml
  internal/time/duration.go
Labels: Review effort 2/5

#6959 Merging to release-5.8.0: [TT-12957] oas uptime testing migration fails on timeout field (#6956)
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/schema/x-tyk-api-gateway.strict.json
  apidef/oas/testdata/fixtures/upstream_uptimeTests.yml
  internal/time/duration.go
Labels: Review effort 2/5

#6966 [TT-7815] ensure path params are migrated to OAS
  apidef/oas/operation.go
  apidef/oas/operation_test.go
  apidef/oas/testdata/fixtures/path_params.yml
Labels: bug, Tyk Product Development, Review effort 3/5

#6962 Merging to release-5.8.0: [TT-14276] Gateway panics if Uptime Tests are disabled in config but enabled in API definition (#6960)
  gateway/host_checker_test.go
  gateway/reverse_proxy.go
Labels: bug, Tyk Product Development, Review effort 2/5

#6970 Merging to release-5.8.0: [TT-7815] ensure path params are migrated to OAS (#6966)
  apidef/oas/operation.go
  apidef/oas/operation_test.go
  apidef/oas/testdata/fixtures/path_params.yml
Labels: Review effort 3/5

#6971 Merging to release-5.8: [TT-7815] ensure path params are migrated to OAS (#6966)
  apidef/oas/operation.go
  apidef/oas/operation_test.go
  apidef/oas/testdata/fixtures/path_params.yml
Labels: Review effort 3/5

#6973 [TT-14413] Check for existing params before generating new ones
  apidef/oas/operation.go
  apidef/oas/operation_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#6975 Merging to release-5.8.0: [TT-14413] Check for existing params before generating new ones (#6973)
  apidef/oas/operation.go
  apidef/oas/operation_test.go
Labels: Review effort 2/5

#6974 Merging to release-5.8: [TT-14413] Check for existing params before generating new ones (#6973)
  apidef/oas/operation.go
  apidef/oas/operation_test.go
Labels: Review effort 2/5

#6978 TT-14452, fixed CVEs for v5.8
  go.mod
  go.sum
Labels: bug, Tyk Product Development, Review effort 1/5

#6980 Merging to release-5.8.0: TT-14452, fixed CVEs for v5.8 (#6978)
  go.mod
  go.sum
Labels: Review effort 1/5

#6982 Merging to release-5.8: [TT-12343] Use API endpoint hard timeouts over global timeout setting (#6976)
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
Labels: bug, Tyk Product Development, Review effort 3/5

#6690 [TT-13365] Create json schema script for Bento config validation
  Taskfile.yml
  apidef/streams/bento/schema/bento-config-schema.json
  apidef/streams/bento/schema/generate_bento_config_schema.go
  apidef/streams/bento/schema/generate_bento_config_schema_test.go
  apidef/streams/bento/validator.go
  docs/dev/how-to-generate-bento-config-validation-schema.md
Labels: Tyk Product Development, Story, Review effort [1-5]: 4
