Repository TykTechnologies/tyk, pull requests merged in 2025-08, with the labels that each got.

#7277 [TT-15196] fix docs issue
  apidef/oas/upstream.go
Labels: Tyk Product Development, Story, Review effort 1/5

#7284 [TT-15505] Remove `negate` field as mandatory from the OAS API schema
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/schema/x-tyk-api-gateway.strict.json
  apidef/oas/testdata/urlRewrite-native.json
  apidef/oas/testdata/urlRewrite-oas.json
  apidef/oas/url_rewrite.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7269 [TT-15359]: Added extra jwt validation
  apidef/oas/authentication.go
  apidef/oas/authentication_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/schema/x-tyk-api-gateway.strict.json
  apidef/oas/security.go
  apidef/oas/security_test.go
  gateway/mw_external_oauth.go
  gateway/mw_jwt.go
  gateway/mw_jwt_test.go
Labels: Tyk Product Development, Story, Review effort 3/5

#7298 Revert "Merging to release-5.8: [TT-5588] [OAS] gateway apiKey import generates unnecessary object (#7270)"
  apidef/oas/security.go
  apidef/oas/security_test.go
Labels: bug, Tyk Product Development

#7303 [TT-5588] [OAS] gateway apiKey import generates unnecessary object
  apidef/oas/authentication.go
  apidef/oas/default_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7312 Update release workflow in 5.9.2 pipeline
  .github/workflows/release.yml
Labels: Review effort 2/5

#7324 Merging to release-5.3: [TT-15190] feat: Gateway Resilience Enhancement - Intelligent Auto-Recovery for Nonce Desynchronization (#7267)
  gateway/api_definition.go
  gateway/api_definition_test.go
  gateway/dashboard_recovery.go
  gateway/dashboard_register.go
  gateway/policy.go
  gateway/policy_test.go
  gateway/server.go
Labels: bug, Tyk Product Development

#7321 The debugger reports error traces on the endpoint where the 'Response Body Transform' middleware is used.
  gateway/tracing.go
  gateway/tracing_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7333 [TT-15359]: updated documentation for core claims update
  apidef/oas/authentication.go
  apidef/oas/security.go
Labels: Tyk Product Development, Story, Review effort 2/5

#7320 Deleting an API with the 'Uptime test' feature enabled crashes the Gateway
  gateway/host_checker_manager.go
  gateway/host_checker_manager_test.go
  gateway/server.go
  internal/oasutil/servers.go
  pkg/errpack/errpack.go
Labels: bug, Tyk Product Development, Review effort 2/5
