Repository TykTechnologies/tyk, pull requests merged in 2025-05, with the labels that each got.

#7034 [TT-14666], fix for panic on gateway side when upgrading old oas file
  gateway/api_loader.go
  gateway/api_loader_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7038 Merging to release-5.8: [TT-14666], fix for panic on gateway side when upgrading old oas file (#7034)
  gateway/api_loader.go
  gateway/api_loader_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7039 Merging to release-5.8.1: [TT-14666], fix for panic on gateway side when upgrading old oas file (#7034)
  gateway/api_loader.go
  gateway/api_loader_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7043 Merging to release-5.3.11: TT-14163 when start the rpc set as default in emergency mode (#6910)
  rpc/rpc_client.go
Labels: Review effort 3/5

#7044 Merging to release-5.3: TT-14163 when start the rpc set as default in emergency mode (#6910)
  rpc/rpc_client.go
Labels: Review effort 3/5

#7047 [TT-14794] fix issue where an invalid stream path results in 500
  ee/middleware/streams/middleware.go
  gateway/mw_streaming_test.go
Labels: bug, Tyk Product Development, Review effort 3/5

#7046 [TT-14666] gw panics after updating from 5 0 with oas api
  gateway/api_loader.go
  gateway/api_loader_test.go
Labels: bug, Tyk Product Development

#7048 Merging to release-5.8: [TT-14666] gw panics after updating from 5 0 with oas api (#7046)
  gateway/api_loader.go
  gateway/api_loader_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7049 Merging to release-5.8.1: [TT-14666] gw panics after updating from 5 0 with oas api (#7046)
  gateway/api_loader.go
  gateway/api_loader_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7033 [TT-14253] Unload Streams Properly
  ee/middleware/streams/middleware.go
  ee/middleware/upstreambasicauth/middleware.go
  ee/middleware/upstreamoauth/middleware.go
  gateway/api_loader.go
  gateway/middleware_wrap.go
  internal/graphengine/engine_v2.go
  internal/model/interfaces.go
Labels: bug, Tyk Product Development, Review effort 3/5

#7053 [ TT-14504] Tyk OAS API definition is not available to Response Plugin if no Request Plugin loaded
  gateway/model_apispec.go
  gateway/mw_go_plugin.go
  gateway/res_handler_go_plugin.go
  goplugin/mw_go_plugin_test.go
  test/goplugins/test_goplugin.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7055 Merging to release-5.8: [ TT-14504] Tyk OAS API definition is not available to Response Plugin if no Request Plugin loaded (#7053)
  gateway/model_apispec.go
  gateway/mw_go_plugin.go
  gateway/res_handler_go_plugin.go
  goplugin/mw_go_plugin_test.go
  test/goplugins/test_goplugin.go
Labels: Review effort 2/5

#7056 Merging to release-5.8: [TT-14829] Added External OAuth Deprecated mark in godoc (#7050)
  apidef/api_definitions.go
  apidef/oas/security.go
Labels: Review effort 1/5

#7057 [TT-14252] Add customValidationRule interface to generate_bento_config_schema script
  apidef/streams/bento/schema/bento-config-schema.json
  apidef/streams/bento/schema/generate_bento_config_schema.go
  apidef/streams/bento/schema/generate_bento_config_schema_test.go
  docs/dev/how-to-generate-bento-config-validation-schema.md
Labels: bug, Tyk Product Development, Review effort 3/5

#7054 [TT-13779] POST form parameters are not logged for Tyk OAS APIs
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
  gateway/testutil.go
Labels: bug, Tyk Product Development, Review effort 3/5

#7059 Merging to release-5.8: [TT-13779] POST form parameters are not logged for Tyk OAS APIs (#7054)
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
  gateway/testutil.go
Labels: Review effort 3/5

#7058 [TT-13924]: updated go mod for kafka datasource
  go.mod
  go.sum
Labels: bug, Tyk Product Development, Review effort 2/5

#7061 [TT-14868] Request Body Not Recorded When Transfer-Encoding: chunked
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7062 Merging to release-5.8: [TT-14868] Request Body Not Recorded When Transfer-Encoding: chunked (#7061)
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7064 Tyk OAS API definition is not available to Response Plugin if no Request Plugin loaded
  .gitignore
  goplugin/mw_go_plugin_test.go
  test/goplugins/test_goplugin.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7073 Merging to release-5.8: [TT-13924]: updated go mod for kafka datasource (#7058)
  go.mod
  go.sum
Labels: Review effort 2/5

#7074 [TT-13924]:fix an issue that causes subscription to panic on start on 5.8
  internal/graphengine/engine_v2.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7052 [TT-10496] GRPC plugins do not work with service names
  gateway/coprocess_grpc.go
  gateway/coprocess_grpc_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7078 Merging to release-5.8: [TT-14794][TT-14946] fix issue where an invalid stream path results in 500 (#7047)
  ee/middleware/streams/middleware.go
  gateway/mw_streaming_test.go
Labels: Review effort 2/5

#7081 Merging to release-5.8: [TT-11387] Unhelpful error messages in UI when creating APIs via OpenAPI import (#7080)
  apidef/oas/default.go
Labels: Review effort 1/5

#7088 [TT-14879] Tyk Dashboard should use /api/apis/streams endpoints to create and import Tyk Stream APIs
  apidef/streams/bento/schema/bento-config-schema.json
Labels: bug, Tyk Product Development, Review effort 2/5

#7089 Merging to release-5.8: [TT-14253] Unload Streams Properly (#7033)
  ee/middleware/streams/middleware.go
  ee/middleware/upstreambasicauth/middleware.go
  ee/middleware/upstreamoauth/middleware.go
  gateway/api_loader.go
  gateway/middleware_wrap.go
  internal/graphengine/engine_v2.go
  internal/model/interfaces.go
Labels: Review effort 3/5
