Repository TykTechnologies/tyk, pull requests merged in 2025-02, with the labels that each got.

#6842 [TT-11909]: fix oas bug on session lifetime and add respect expiry
  apidef/api_definitions.go
  apidef/migration.go
  apidef/migration_test.go
  apidef/oas/authentication.go
  apidef/oas/authentication_test.go
  apidef/oas/linter_test.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: Tyk Product Development, Story, Review effort [1-5]: 3

#6853 [TT-12884] add batch requests support to OAS
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/server.go
  apidef/oas/server_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6856 [TT-7249] Flaky TestJWTSessionExpiresAtValidationConfigs
  gateway/mw_jwt_test.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 1

#6848 [TT-13910]: Removed disable expire analytics and added customRetentionPeriod OAS
  apidef/api_definitions.go
  apidef/migration.go
  apidef/migration_test.go
  apidef/oas/linter_test.go
  apidef/oas/middleware.go
  apidef/oas/middleware_test.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  gateway/handler_error.go
  gateway/handler_success.go
  gateway/proxy_muxer.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 4

#6859 [TT-12638] Added PreserveHostHeader to OAS functionality
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/upstream.go
  apidef/oas/upstream_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 3

#6862 Tt 13890 request debug endpoint
  .redocly.lint-ignore.yaml
  gateway/gateway_test.go
  gateway/tracing.go
  swagger.yml
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6850 [TT-11908] add request signing to OAS upstream authentication
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/upstream.go
  apidef/oas/upstream_test.go
  gateway/mw_request_signing.go
  gateway/mw_request_signing_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6860 [TT-13998] make url of X-Tyk-Upstream optional when loadBalancing is present
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/validator.go
Labels: bug, Tyk Product Development, Review effort [1-5]: 2

#6827 [DX-1780]Generate test for tyk gateway swagger
  .github/workflows/release-tests.yml
  .gitignore
  ci/tests/specs/.env.example
  ci/tests/specs/README.md
  ci/tests/specs/Taskfile.yml
  ci/tests/specs/config/certs.js
  ci/tests/specs/config/portman-cli-options.json
  ci/tests/specs/config/portmanconfig.json
  ci/tests/specs/config/prescript.js
  ci/tests/specs/config/tyk.standalone.conf
  ci/tests/specs/docker-compose.yml
  ci/tests/specs/package.json
  ci/tests/specs/test.sh
  ci/tests/specs/testdata/populate_gateway_test_data.yaml
  swagger.yml
Labels: Story, Review effort [1-5]: 4, Developer eXperience

#6865 [TT-14022] [release-5.7] exp/modcheck: Update go.mod dependencies
  go.mod
  go.sum
Labels: Review effort [1-5]: 2

#6866 [TT-14024] [release-5.3] exp/modcheck: Update go.mod dependencies
  go.mod
  go.sum
Labels: Review effort [1-5]: 2

#6852 [TT-12957] OAS Uptime Tests migrations
  apidef/api_definitions.go
  apidef/oas/Taskfile.yml
  apidef/oas/linter_test.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/schema/x-tyk-api-gateway.strict.json
  apidef/oas/upstream.go
  apidef/oas/upstream_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 3

#6855 TT-12965: Improve performance of ctx.GetOASDefinition/GetDefinition
  Taskfile.yml
  apidef/oas/oas.go
  apidef/oas/oas_test.go
  coprocess/Taskfile.yml
  ctx/Taskfile.yml
  ctx/ctx.go
  ctx/ctx_test.go
  gateway/mw_go_plugin.go
  go.mod
  go.sum
  internal/reflect/clone.go
  internal/reflect/clone_test.go
Labels: Tyk Product Development, Story

#6867 [TT-13477] upstream oauth event handling
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/streams/schema/x-tyk-api-gateway.json
  ee/middleware/upstreamoauth/model.go
  ee/middleware/upstreamoauth/provider.go
  gateway/event_system.go
  internal/event/event.go
  templates/default_webhook.json
Labels: Tyk Product Development, Story, Review effort [1-5]: 3

#6677 TT-14070: [Testing/Concurrency] Test gateway lifecycle, enable start/stop parallelism
  apidef/oas/Taskfile.yml
  apidef/oas/schema/x-tyk-api-gateway.strict.json
  cli/cli.go
  config/config.go
  gateway/gateway_test.go
  gateway/server.go
  gateway/testutil.go
  go.mod
  go.sum
  templates/doc.go
  tests/lifecycle/Taskfile.yml
  tests/lifecycle/lifecycle_test.go
Labels: Review effort 4/5

#6871 TT-14085: Remove the pmylund/go-cache dependency
  dnscache/storage.go
  gateway/server.go
  gateway/testutil.go
  go.mod
  go.sum
  internal/cache/Taskfile.yml
  internal/cache/cache.go
  internal/cache/cache_test.go
  internal/cache/const.go
  internal/cache/item.go
  internal/cache/item_test.go
  internal/cache/janitor.go
  internal/cache/janitor_test.go
  internal/cache/repository.go
  internal/cache/repository_test.go
  regexp/cache.go
Labels: Tyk Product Development, Story, Review effort 4/5

#6878 [TT-13657]: modified json schema for protocol
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/schema/x-tyk-api-gateway.strict.json
Labels: Tyk Product Development, Story, Review effort 2/5

#6873 TT-14089 load apis from emergency mode, wait for connection considers emergency mode
  gateway/server.go
  go.mod
  go.sum
  rpc/rpc_client.go
Labels: bug, Tyk Product Development, Review effort 3/5

#6884 Merging to release-5.3: TT-14089 load apis from emergency mode, wait for connection considers emergency mode (#6873)
  gateway/server.go
  go.mod
  go.sum
  rpc/rpc_client.go
Labels: Review effort 3/5

#6885 Merging to release-5.3.10: TT-14089 load apis from emergency mode, wait for connection considers emergency mode (#6873)
  gateway/server.go
  go.mod
  go.sum
  rpc/rpc_client.go
Labels: Review effort 3/5

#6886 Merging to release-5.7: TT-14089 load apis from emergency mode, wait for connection considers emergency mode (#6873)
  gateway/server.go
  go.mod
  go.sum
  rpc/rpc_client.go
Labels: Review effort 3/5

#6887 Merging to release-5.7.2: TT-14089 load apis from emergency mode, wait for connection considers emergency mode (#6873)
  gateway/server.go
  go.mod
  go.sum
  rpc/rpc_client.go
Labels: Review effort 3/5

#6883 [TT-13440] correctly sync multi-value response headers with coprocess middleware
  gateway/coprocess.go
  gateway/coprocess_test.go
Labels: bug, Tyk Product Development, Review effort 3/5

#6879 TT-14059: Add migration test fixtures
  apidef/oas/Taskfile.yml
  apidef/oas/fixtures_test.go
  apidef/oas/oas.go
  apidef/oas/testdata/fixtures/plugins.yml
  apidef/oas/testdata/fixtures/service_discovery.yml
  apidef/oas/upstream.go
  docs/dev/oas-fixtures.md
  go.mod
  go.sum
  internal/reflect/flatten.go
Labels: bug, Tyk Product Development, Review effort 4/5

#6888 TT-14132: Update sonarcloud sonarqube scan
  .github/workflows/ci-tests.yml
Labels: Tyk Product Development, Task, Review effort 2/5

#6891 Merging to release-5.3: [TT-13440] correctly sync multi-value response headers with coprocess middleware (#6883)
  gateway/coprocess.go
  gateway/coprocess_test.go
Labels: Review effort 3/5

#6893 [TT-14100] fix requireSession in OAS for custom auth plugins
  apidef/oas/authentication.go
  apidef/oas/authentication_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/schema/x-tyk-api-gateway.strict.json
Labels: bug, Tyk Product Development, Review effort 2/5

#6889 TT-14110, TT-14112, TT-14103: Implement ignoreCase, preserveTrailingSlash, remove multipleOf
  apidef/oas/fixtures_test.go
  apidef/oas/middleware.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/schema/x-tyk-api-gateway.strict.json
  apidef/oas/testdata/fixtures/middleware_global.yml
  apidef/oas/testdata/fixtures/plugins.yml
  apidef/oas/testdata/fixtures/upstream_flags.yml
  apidef/oas/upstream.go
  apidef/oas/validator.go
Labels: Tyk Product Development, Story, Review effort 4/5

#6896 TT-14154: [test only] fix golangci-lint base branch for merges
  .github/workflows/ci-tests.yml
Labels: Tyk Product Development, Task, Review effort 2/5

#6895 [TT-14084] External OAuth is migrated as Keyless
  apidef/oas/security.go
  apidef/oas/security_test.go
Labels: bug, Tyk Product Development, Review effort 3/5

#6900 [TT-14178] Temporarily revert strict oas schema usage
  apidef/oas/validator.go
Labels: Review effort 4/5

#6899 [TT-14111] add support for rate limit and quota flags in OAS
  apidef/oas/middleware.go
  apidef/oas/middleware_test.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/schema/x-tyk-api-gateway.strict.json
  apidef/oas/testdata/fixtures/middleware_global.yml
Labels: Tyk Product Development, Story, Review effort 4/5

#6880 [TT-13660] add support for log event handler to OAS definitions
  apidef/api_definitions.go
  apidef/api_definitions_test.go
  apidef/oas/event.go
  apidef/oas/event_test.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/schema/x-tyk-api-gateway.strict.json
  internal/event/event.go
Labels: Tyk Product Development, Story, Review effort 4/5

#6904 [TT-13936] Improve RPC connection handling for user key reset events
  gateway/redis_signals.go
  gateway/rpc_storage_handler.go
Labels: Tyk Product Development, Story, Review effort 3/5

#6902 TT-14192: Consistent use of imported package for gojsonschema, lint
  .golangci.yml
  apidef/oas/linter_test.go
  apidef/oas/validator.go
  apidef/streams/validator.go
  cli/linter/linter.go
  internal/service/gojsonschema/gojsonschema.go
Labels: Review effort 3/5

#6906 TT-14110: Cover migration of ignoreCase for classic
  apidef/oas/middleware.go
  apidef/oas/testdata/fixtures/middleware_global.yml
Labels: Tyk Product Development, Story, Review effort 2/5

#6894 TT-7306: Migrate Mock Response from Classic API Definition to OAS API Definition
  apidef/oas/operation.go
  apidef/oas/operation_test.go
  apidef/oas/testdata/fixtures/mock_response.yml
Labels: bug, Tyk Product Development, Review effort 4/5

#6907 [TT-14200] add support to disable log event handlers and custom event handlers
  gateway/event_handler_jsvm.go
  gateway/event_handler_jsvm_test.go
  gateway/event_handler_log.go
  gateway/event_handler_log_test.go
  gateway/event_handler_webhooks.go
  gateway/event_system.go
  gateway/event_system_test.go
Labels: bug, Tyk Product Development, Review effort 4/5

#6909 TT-14059: Extend service discovery tests and fixtures
  apidef/oas/fixtures_test.go
  apidef/oas/linter_test.go
  apidef/oas/schema/build.sh
  apidef/oas/schema/x-tyk-api-gateway.strict.json
  apidef/oas/testdata/fixtures/service_discovery.yml
  apidef/oas/upstream.go
Labels: bug, Tyk Product Development, Review effort 3/5

#6908 TT-14183: Fix uptimetests migrations, add fixtures, enabled flag
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/schema/x-tyk-api-gateway.strict.json
  apidef/oas/testdata/fixtures/upstream_uptimeTests.yml
  apidef/oas/upstream.go
  apidef/oas/upstream_test.go
Labels: Tyk Product Development, Sub-task, Review effort 4/5
