Repository TykTechnologies/tyk, pull requests merged in 2025-06, with the labels that each got.

#7092 [TT-14731] Add a flag to enable all bento inputs/outputs
  apidef/streams/bento/validator.go
  apidef/streams/bento/validator_test.go
  apidef/streams/validator.go
  apidef/streams/validator_test.go
Labels: Tyk Product Development, Story, Review effort 2/5

#7041 [TT-14863] Replace github.com/TykTechnologies/kin-openapi with github.com/getkin/kin-openapi
  apidef/adapter/openapi.go
  apidef/oas/authentication.go
  apidef/oas/default.go
  apidef/oas/default_test.go
  apidef/oas/example.go
  apidef/oas/example_test.go
  apidef/oas/fixtures_test.go
  apidef/oas/import_test.go
  apidef/oas/oas.go
  apidef/oas/oas_test.go
  apidef/oas/old_oas.go
  apidef/oas/operation.go
  apidef/oas/operation_test.go
  apidef/oas/root_test.go
  apidef/oas/security.go
  apidef/oas/security_test.go
  apidef/oas/validator_test.go
  apidef/streams/validator_test.go
  ctx/ctx_test.go
  gateway/api.go
  gateway/api_definition.go
  gateway/api_definition_test.go
  gateway/api_test.go
  gateway/looping_test.go
  gateway/mock_response.go
  gateway/mock_response_test.go
  gateway/model_apispec.go
  gateway/mw_oas_validate_request.go
  gateway/mw_oas_validate_request_test.go
  gateway/mw_streaming_test.go
  gateway/mw_version_check.go
  gateway/testutil.go
  go.mod
  go.sum
  goplugin/mw_go_plugin_test.go
  internal/oasutil/paths.go
  internal/oasutil/paths_test.go
Labels: Tyk Product Development, Story, Review effort 4/5

#7104 [TT-13740]: update mod and updated apidef
  apidef/adapter/asyncapi_test.go
  apidef/adapter/gqlengineadapter/adapter_proxy_only.go
  apidef/adapter/gqlengineadapter/adapter_supergraph.go
  apidef/adapter/gqlengineadapter/adapter_udg.go
  apidef/adapter/gqlengineadapter/utils_engine_v2.go
  apidef/adapter/gqlengineadapter/utils_engine_v2_test.go
  apidef/adapter/openapi_test.go
  apidef/api_definitions.go
  apidef/oas/oas_test.go
  go.mod
  go.sum
Labels: Tyk Product Development, Story, Review effort 2/5

#7110 [QA-1608 release-5.8] Github template update
  .github/workflows/release.yml
  ci/goreleaser/goreleaser.yml
Labels: Review effort 3/5

#7116 [TT-14731] Add a flag to enable all bento inputs/outputs
  config/config.go
Labels: Tyk Product Development, Story, Review effort 1/5

#7118 Merging to release-5.8: [TT-14244] Bump go, set godebug for compatibility (#6963)
  go.mod
Labels: Review effort 1/5

#7120 [TT-15065] Mock response stops working after kin-openapi upgrade
  apidef/oas/example.go
  gateway/mock_response.go
  gateway/mock_response_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7122 Merging to release-5.8: [TT-10496] GRPC plugins do not work with service names (#7052)
  gateway/coprocess_grpc.go
  gateway/coprocess_grpc_test.go
Labels: Review effort 2/5

#7121 Merging to release-5.8: [TT-10496] gRPC plugins do not terminate gracefully and cannot be load balanced (#7111)
  cli/linter/schema.json
  config/config.go
  gateway/coprocess_grpc.go
Labels: Review effort 2/5

#7125 [TT-14621]corrected prefix for certificates (#7094) trial 3
  README.md
  storage/mdcb_storage.go
  storage/mdcb_storage_test.go
Labels: Review effort 2/5

#7126 [TT-14299] add mqtt and websocket load generator for streams testing
  .golangci.yml
  tests/streams/scripts/README.md
  tests/streams/scripts/amqp_load_generator.go
  tests/streams/scripts/load_gen.go
  tests/streams/scripts/mqtt_load_generator.go
  tests/streams/scripts/websocket_load_generator.go
Labels: Tyk Product Development, Story, Review effort 4/5

#7119 [TT-14857] Updating dependencies to fix CVEs
  go.mod
  go.sum
Labels: Tyk Product Development, Story, Review effort 2/5

#7101 [TT-7932] Errors migrating some versioned APIs to OAS
  apidef/oas/root.go
  apidef/oas/root_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7135 Merging to release-5.8: [TT-7932] Errors migrating some versioned APIs to OAS (#7101)
  apidef/oas/root.go
  apidef/oas/root_test.go
Labels: Review effort 2/5

#7134 Merging to release-5.9: [TT-7932] Errors migrating some versioned APIs to OAS (#7101)
  apidef/oas/root.go
  apidef/oas/root_test.go
Labels: Review effort 2/5

#7138 Mdcb dns rpc critical fix branch
  gateway/policy.go
  gateway/rpc_storage_handler.go
  gateway/rpc_storage_handler_test.go
  gateway/server.go
  gateway/server_test.go
  rpc/dns_resolver.go
  rpc/dns_resolver_test.go
  rpc/rpc_client.go
  rpc/utils.go
  rpc/utils_test.go
Labels: Review effort 5/5

#7113 [TT-14914] No response middleware information in Tyk OAS API Debugger
  .gitignore
  apidef/oas/builder.go
  apidef/oas/middleware.go
  gateway/api_loader.go
  gateway/coprocess.go
  gateway/middleware.go
  gateway/middleware_decorators.go
  gateway/res_cache.go
  gateway/res_handler_go_plugin.go
  gateway/res_handler_header_injector.go
  gateway/res_handler_jq_transform_dummy.go
  gateway/res_handler_transform.go
  gateway/server.go
  gateway/tracing.go
  gateway/tracing_test.go
  go.mod
  go.sum
Labels: bug, Tyk Product Development, Review effort 4/5

#7140 Merging to release-5.9: [TT-14914] No response middleware information in Tyk OAS API Debugger (#7113)
  .gitignore
  apidef/oas/builder.go
  apidef/oas/middleware.go
  gateway/api_loader.go
  gateway/coprocess.go
  gateway/middleware.go
  gateway/middleware_decorators.go
  gateway/res_cache.go
  gateway/res_handler_go_plugin.go
  gateway/res_handler_header_injector.go
  gateway/res_handler_jq_transform_dummy.go
  gateway/res_handler_transform.go
  gateway/server.go
  gateway/tracing.go
  gateway/tracing_test.go
  go.mod
  go.sum
Labels: Review effort 4/5

#7141 [TT-14839] Update version on swagger yml
  swagger.yml
Labels: Tyk Product Development, Story, Review effort 1/5

#7144 Merging to release-5.9: [TT-14839] Update version on swagger yml (#7141)
  swagger.yml
Labels: Review effort 1/5

#7145 Merging to release-5.9.0: [TT-14839] Update version on swagger yml (#7141)
  swagger.yml
Labels: Review effort 1/5

#7105 [TT-8963] Unable to loop mocked endpoint
  .dockerignore
  .gitignore
  apidef/oas/builder.go
  apidef/oas/header.go
  ci/tests/tracing/scenarios/tyk_tykprotocol_200.yml
  ctx/ctx.go
  gateway/api.go
  gateway/api_definition.go
  gateway/api_definition_test.go
  gateway/api_loader.go
  gateway/model_apispec.go
  gateway/mw_mock_response.go
  gateway/mw_mock_response_test.go
  gateway/mw_oas_validate_request.go
  gateway/mw_version_check.go
  gateway/mw_virtual_endpoint.go
  gateway/reverse_proxy.go
  gateway/tracing.go
  gateway/tracing_test.go
Labels: bug, Tyk Product Development, Review effort 4/5

#7158 [TT-14914] No response middleware information in Tyk OAS API Debugger
  gateway/api_loader.go
  gateway/coprocess.go
  gateway/middleware.go
  gateway/mw_go_plugin.go
  gateway/mw_js_plugin.go
  gateway/mw_mock_response.go
  gateway/mw_redis_cache.go
  gateway/mw_version_check.go
  gateway/mw_virtual_endpoint.go
  gateway/server.go
  gateway/tracing.go
  gateway/tracing_test.go
  internal/oasbuilder/builder.go
Labels: bug, Tyk Product Development, Review effort 4/5
