Repository TykTechnologies/tyk, pull requests merged in 2025-01, with the labels that each got.

#6809 [TT-13766] Bump newrelic dependency
  gateway/api_loader.go
  gateway/middleware.go
  gateway/newrelic.go
  gateway/proxy_muxer.go
  gateway/server.go
  gateway/testutil.go
  go.mod
  go.sum
  internal/service/newrelic/logger.go
  internal/service/newrelic/newrelic.go
  internal/service/newrelic/sink.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6818 [TT-11910]: added tag headers to traffic logs and tests
  apidef/oas/middleware.go
  apidef/oas/middleware_test.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  gateway/cert_old_test.go
Labels: Review effort [1-5]: 3

#6819 Add tests to verify yaml conversions work
  apidef/oas/oas_test.go
  go.mod
  go.sum
Labels: Review effort [1-5]: 3

#6812 [TT-13723] Update to Go 1.23
  .github/workflows/ci-tests.yml
  .github/workflows/plugin-compiler-build.yml
  .github/workflows/release.yml
  .taskfiles/deps.yml
  .taskfiles/test.yml
  Dockerfile
  Taskfile.yml
  ci/images/plugin-compiler/Dockerfile
  gateway/gateway_test.go
  go.mod
  internal/debug2/goroutine.go
  internal/debug2/goroutine_test.go
  tests/system/README.md
  tests/system/goroutine_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6817 [TT-10070] Fix/sanitize error logging
  config/config.go
  gateway/api.go
  gateway/api_loader.go
  gateway/coprocess_api.go
  gateway/coprocess_id_extractor_test.go
  gateway/delete_api_cache.go
  gateway/event_handler_webhooks.go
  gateway/gateway_test.go
  gateway/health_check.go
  gateway/host_checker.go
  gateway/host_checker_manager.go
  gateway/host_checker_manager_test.go
  gateway/mw_external_oauth.go
  gateway/mw_jwt.go
  gateway/mw_oauth2_auth_ee.go
  gateway/oauth_manager.go
  gateway/redis_logrus_hook.go
  gateway/rpc_backup_handlers.go
  gateway/rpc_storage_handler.go
  gateway/server.go
  gateway/server_test.go
  gateway/testutil.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6823 [TT-13723] [release-5.3] Update to Go 1.23
  .github/workflows/ci-tests.yml
  .github/workflows/plugin-compiler-build.yml
  .github/workflows/release.yml
  .taskfiles/deps.yml
  .taskfiles/hooks.yml
  .taskfiles/test.yml
  Dockerfile
  Taskfile.yml
  ci/images/plugin-compiler/Dockerfile
  gateway/gateway_test.go
  go.mod
  internal/debug2/goroutine.go
  internal/debug2/goroutine_test.go
  tests/system/README.md
  tests/system/goroutine_test.go
Labels: Review effort [1-5]: 4

#6824 [TT-11896] Add OAS IPAccessControl
  apidef/api_definitions.go
  apidef/migration.go
  apidef/migration_test.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/server.go
  apidef/oas/server_test.go
  apidef/schema.json
  docs/dev/apidef-oas.md
  gateway/mw_ip_blacklist.go
  gateway/mw_ip_blacklist_test.go
  gateway/mw_ip_whitelist.go
  gateway/mw_ip_whitelist_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6822 implement api-level request size limit for oas (TT-11459)
  apidef/api_definitions.go
  apidef/oas/middleware.go
  apidef/oas/middleware_test.go
  apidef/oas/oas_test.go
  apidef/oas/oasutil.go
  apidef/oas/schema/x-tyk-api-gateway.json
  docs/dev/apidef-oas.md
  gateway/mw_request_size_limit.go
  gateway/mw_request_size_limit_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6825 [TT-11912]: Added Analytics expiry period to OAS
  apidef/api_definitions.go
  apidef/migration.go
  apidef/migration_test.go
  apidef/oas/linter_test.go
  apidef/oas/middleware.go
  apidef/oas/middleware_test.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/schema.json
  gateway/handler_error.go
  gateway/handler_success.go
  gateway/proxy_muxer.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6829 [TT-11913] Add custom analytics plugins configuration to OAS
  apidef/api_definitions.go
  apidef/oas/middleware.go
  apidef/oas/middleware_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6830 add load balancing to oas configuration (TT-881)
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/upstream.go
  apidef/oas/upstream_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6826 [TT-13819] Benchmark updates, session limiter workaround for test goroutine leak
  .github/CODEOWNERS
  bin/ci-benchmark.sh
  gateway/api_definition_test.go
  gateway/event_system_test.go
  gateway/mw_basic_auth_test.go
  gateway/mw_jwt_test.go
  gateway/mw_transform_test.go
  gateway/mw_version_check_test.go
  gateway/oauth_manager_test.go
  gateway/res_handler_header_injector_test.go
  gateway/session_manager.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6831 Merging to release-5.3: [TT-13819] Benchmark updates, session limiter workaround for test goroutine leak (#6826)
  .github/CODEOWNERS
  bin/ci-benchmark.sh
  gateway/api_definition_test.go
  gateway/event_system_test.go
  gateway/mw_basic_auth_test.go
  gateway/mw_jwt_test.go
  gateway/mw_transform_test.go
  gateway/mw_version_check_test.go
  gateway/oauth_manager_test.go
  gateway/res_handler_header_injector_test.go
  gateway/session_manager.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6834 Merging to release-5.2: [TT-13819] Benchmark updates, session limiter workaround for test goroutine leak (#6826)
  .github/CODEOWNERS
  Makefile
  bin/ci-benchmark.sh
  certs/mock/mock.go
  gateway/api_definition_test.go
  gateway/event_system_test.go
  gateway/mw_basic_auth_test.go
  gateway/mw_jwt_test.go
  gateway/mw_transform_test.go
  gateway/mw_version_check_test.go
  gateway/res_handler_header_injector_test.go
Labels: Review effort [1-5]: 4

#6832 Merging to release-5-lts: [TT-13819] Benchmark updates, session limiter workaround for test goroutine leak (#6826)
  .github/CODEOWNERS
  bin/ci-benchmark.sh
  gateway/api_definition_test.go
  gateway/event_system_test.go
  gateway/mw_basic_auth_test.go
  gateway/mw_jwt_test.go
  gateway/mw_transform_test.go
  gateway/mw_version_check_test.go
  gateway/oauth_manager_test.go
  gateway/res_handler_header_injector_test.go
Labels: Tyk Product Development, Story

#6835 [TT-11909]: Added Session Lifetime to OAS
  apidef/api_definitions.go
  apidef/migration.go
  apidef/migration_test.go
  apidef/oas/authentication.go
  apidef/oas/linter_test.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/schema.json
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6837 fix omitempty on some fields for LoadBalancing (TT-881)
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/upstream.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 2

#6838 [TT-2539] Refactor hash and token apis under internal/crypto, leave aliases
  gateway/host_checker_test.go
  internal/crypto/hash.go
  internal/crypto/token.go
  storage/alias.go
  storage/storage.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 3

#6841 [TT-2539] Transaction logs
  cli/linter/schema.json
  config/config.go
  gateway/handler_error.go
  gateway/handler_success.go
  gateway/middleware.go
  internal/httputil/Taskfile.yml
  internal/httputil/accesslog/filter.go
  internal/httputil/accesslog/filter_test.go
  internal/httputil/accesslog/record.go
  internal/httputil/accesslog/record_test.go
  tests/accesslog/access_log_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4

#6846 [TT-13657]: Add protocol and port to oas
  apidef/oas/linter_test.go
  apidef/oas/oas_test.go
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/server.go
  apidef/oas/server_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 3

#6849 TT-2539 - renamed access log fields
  config/config.go
  internal/httputil/accesslog/record.go
  internal/httputil/accesslog/record_test.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 2

#6844 [TT-13820] Fix code whitespace style consistency
  .github/workflows/ci-tests.yml
  .golangci.yml
  .taskfiles/deps.yml
  .taskfiles/hooks.yml
  .taskfiles/lint.yml
  Taskfile.yml
  certs/manager_test.go
  certs/mock/mock.go
Labels: Tyk Product Development, Story, Review effort [1-5]: 4
