Repository TykTechnologies/tyk, pull requests merged in 2025-09, with the labels that each got.

#7328 [OAS] gateway apiKey import generates unnecessary object
  apidef/oas/authentication.go
  apidef/oas/default_test.go
  apidef/oas/security.go
  apidef/oas/security_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7332 [TT-15379][TT-15383] introduce certificate expiry checks and events
  apidef/oas/schema/x-tyk-api-gateway.json
  apidef/oas/schema/x-tyk-api-gateway.strict.json
  apidef/streams/schema/x-tyk-api-gateway.json
  cli/linter/schema.json
  config/config.go
  config/config_test.go
  config/testdata/cert_monitor_defaults_with_env_overrides.json
  config/testdata/cert_monitor_warning_1day_check_1sec_event_1sec_minimal.json
  config/testdata/expect.cert_monitor_defaults_with_env_overrides.json
  config/testdata/expect.cert_monitor_warning_1day_check_1sec_event_1sec_minimal.json
  gateway/api_loader.go
  gateway/event_handler_webhooks.go
  gateway/event_handler_webhooks_test.go
  gateway/event_system.go
  gateway/mw_certificate_check.go
  gateway/mw_certificate_check_benchmark_test.go
  gateway/mw_certificate_check_integration_test.go
  gateway/mw_certificate_check_test.go
  go.mod
  internal/certcheck/batcher.go
  internal/certcheck/batcher_mock.go
  internal/certcheck/batcher_test.go
  internal/certcheck/cache.go
  internal/certcheck/cache_mock.go
  internal/certcheck/cache_test.go
  internal/certcheck/model.go
  internal/event/event.go
  templates/default_webhook.json
Labels: Tyk Product Development, Story

#7330 Body transform middleware not applied when URL rewrite pattern contains regex
  gateway/res_handler_transform_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7344 [TT-15684]: Add normalize step to OAS api
  apidef/oas/authentication.go
  apidef/oas/oas.go
  apidef/oas/oas_test.go
  apidef/oas/security.go
  apidef/oas/security_test.go
  gateway/reverse_proxy_test.go
Labels: Tyk Product Development, Sub-task, Review effort 2/5

#7346 [TT-15399] minimal godocs update on external services config
  config/external_service.go
Labels: Tyk Product Development, Story

#7338 Request Body Transform MW and Header Transform MW are not sufficiently logged in the debugger
  gateway/mw_modify_headers.go
  gateway/mw_transform.go
  gateway/res_handler_header_injector.go
  gateway/res_handler_transform.go
  gateway/tracing_test.go
  internal/oasbuilder/builder.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7361 Tt 15671 fix schema json unit tests
  apidef/oas/security_test.go
Labels: Tyk Product Development, Story, Review effort 2/5

#7364 Replace probe workflows with visor
  .github/workflows/connectivity-review.yml
  .github/workflows/dependency-review.yml
  .github/workflows/performance-review.yml
  .github/workflows/probe.yml
  .github/workflows/security-review.yml
  .github/workflows/visor.yaml
  .probe/connectivity-reviewer.md
  .probe/dependency-impact-reviewer.md
  .probe/performance-reviewer.md
  .probe/security-reviewer.md
  .visor.yaml
Labels: Review effort 2/5

#7363 Add security_requirements field to schema and refactor JWT and Basic Auth handling
  apidef/oas/security.go
  apidef/oas/security_test.go
  apidef/schema.json
Labels: Tyk Product Development, Story, Review effort 2/5

#7377 [TT-15718] Upgrade graphql-go-tools dependency to fix CVE-2025-54388
  go.mod
  go.sum
Labels: Review effort 2/5

#7384 [TT-15868] Fixing panic when using JWT as a second authentication method in compliant mode
  apidef/oas/security.go
  apidef/oas/security_test.go
  gateway/mw_auth_or_wrapper_test.go
Labels: Tyk Product Development, Sub-task, Review effort 4/5

#7386 [TT-15869] cooldown defaults not working and minor datetime format adjustments
  gateway/event_handler_webhooks.go
  gateway/event_handler_webhooks_test.go
  internal/certcheck/batcher.go
  internal/certcheck/batcher_test.go
  templates/default_webhook.json
Labels: bug, Tyk Product Development, Review effort 2/5
