Repository TykTechnologies/tyk, pull requests merged in 2025-04, with the labels that each got.

#6983 Merging to release-5.8: [TT-14357]: fixed issue with stale context in UDG (#6977)
  gateway/mw_graphql.go
  gateway/mw_request_size_limit_test.go
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
  internal/cache/cache_test.go
  internal/graphengine/engine_v2.go
  internal/graphengine/graphql_go_tools_v1.go
Labels: Review effort 4/5

#6984 [TT-12442] necessary changes for new licensing logic
  gateway/api_definition.go
  gateway/policy.go
  gateway/server.go
  gateway/testutil.go
Labels: bug, Tyk Product Development, Review effort 2/5

#6985 [TT-12442] changes required in gateway for new licensing to work
  gateway/api_definition.go
  gateway/dashboard_register.go
  gateway/policy.go
Labels: bug, Tyk Product Development, Review effort 2/5

#6988 [TT-12442] Force gw reload after registration to have synced polciies and apis
  gateway/dashboard_register.go
  gateway/reverse_proxy_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#6989 [SYSE-401] Use go 1.23 for builds
  .github/workflows/release.yml
  ci/Dockerfile.distroless
  ci/Dockerfile.std
Labels: Review effort 4/5

#6986 [TT-14357]: fixed issue with stale context in UDG
  gateway/mw_graphql.go
  gateway/mw_request_size_limit_test.go
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
  internal/graphengine/engine_v2.go
  internal/graphengine/graphql_go_tools_v1.go
Labels: Review effort 3/5

#6991 [TT-14518] Exclude swagger.yml from sonarcloud analysis
  .github/workflows/ci-tests.yml
Labels: Tyk Product Development, Story, Review effort 1/5

#6981 Merging to release-5.3: [TT-12343] Use API endpoint hard timeouts over global timeout setting (#6976)
  gateway/reverse_proxy.go
  gateway/reverse_proxy_test.go
Labels: bug, Tyk Product Development, Review effort 3/5

#6987 [TT-13277] Improve API listen path sorting to prioritize static segments over parameters
  gateway/api_loader.go
  gateway/api_loader_test.go
Labels: bug, Tyk Product Development, Review effort 3/5

#6996 Merging to release-5.3: [TT-13277] Improve API listen path sorting to prioritize static segments over parameters (#6987)
  gateway/api_loader.go
  gateway/api_loader_test.go
Labels: bug, Tyk Product Development, Review effort 3/5

#6995 Merging to release-5.8: [TT-13277] Improve API listen path sorting to prioritize static segments over parameters (#6987)
  gateway/api_loader.go
  gateway/api_loader_test.go
Labels: bug, Tyk Product Development, Review effort 3/5

#6992 [TT-12343] Improve Timeout Test Coverage and Consistency in TestTimeoutPrioritization
  gateway/reverse_proxy_test.go
Labels: bug, Tyk Product Development, Review effort 3/5

#6997 Merging to release-5.8: [TT-12343] Improve Timeout Test Coverage and Consistency in TestTimeoutPrioritization (#6992)
  gateway/reverse_proxy_test.go
Labels: bug, Tyk Product Development, Review effort 3/5

#3726 [TT-14149] Added more details to the ssl_certificate config
  config/config.go
Labels: Tyk Product Development, Task, Story, Review effort 2/5

#7002 Merging to release-5.8: [TT-14518] Exclude swagger.yml from sonarcloud analysis (#6991)
  .github/workflows/ci-tests.yml
Labels: Review effort 1/5

#6972 TT-14365: internal/policy: add restricted_types behaviour test
  config/config.go
  internal/policy/Taskfile.yml
  internal/policy/apply.go
  internal/policy/apply_test.go
  internal/policy/testdata/policies.json
Labels: Review effort 2/5

#7003 [TT-1428]: added bloblang to test for json schema
  apidef/streams/validator_test.go
Labels: Tyk Product Development, Sub-task, Review effort 2/5

#7006 [SYSE-372 release-5.3] Implement custom rules for enterprise artifacts in package promotion
  ci/goreleaser/goreleaser.yml
Labels: Review effort 2/5

#7005 [SYSE-372 master] Implement custom rules for enterprise artifacts in package promotion
  ci/Dockerfile.distroless
  ci/Dockerfile.std
  ci/goreleaser/goreleaser.yml
Labels: Story, Review effort 3/5, SysE

#7008 Merging to release-5.8: TT-14365: internal/policy: add restricted_types behaviour test (#6972)
  config/config.go
  internal/policy/Taskfile.yml
  internal/policy/apply.go
  internal/policy/apply_test.go
  internal/policy/testdata/policies.json
Labels: Review effort 2/5

#7004 [TT-14300] Add support for AMQP 0.9 and 1.0
  apidef/streams/bento/schema/bento-config-schema.json
  apidef/streams/bento/schema/generate_bento_config_schema.go
  ee/middleware/streams/stream.go
  gateway/mw_streaming_amqp_test.go
  go.mod
  go.sum
Labels: Tyk Product Development, Story, Review effort 4/5

#7009 [ TT-14298]: Added support for bloblang
  apidef/streams/bento/schema/bento-config-schema.json
  apidef/streams/bento/schema/generate_bento_config_schema.go
  apidef/streams/validator_test.go
  gateway/mw_streaming_test.go
Labels: Tyk Product Development, Story

#7010 [TT-14431]: add mqtt to json schema
  apidef/streams/bento/schema/bento-config-schema.json
  apidef/streams/bento/schema/generate_bento_config_schema.go
Labels: Tyk Product Development, Sub-task, Review effort 3/5

#7012 [TT-14300] Simple AMQP load generator tool for amqp_1 and amqp_0_9
  tests/streams/scripts/README.md
  tests/streams/scripts/amqp_load_generator.go
Labels: Tyk Product Development, Story, Review effort 3/5

#7015 Merging to release-5.8: [TT-12442] necessary changes for new licensing logic (#6984)
  gateway/api_definition.go
  gateway/policy.go
  gateway/server.go
  gateway/testutil.go
Labels: Review effort 2/5

#7014 Merging to release-5.8: [TT-12442] changes required in gateway for new licensing to work (#6985)
  gateway/api_definition.go
  gateway/dashboard_register.go
  gateway/policy.go
Labels: Review effort 2/5

#7013 Merging to release-5.8: [TT-12442] Force gw reload after registration to have synced polciies and apis (#6988)
  gateway/dashboard_register.go
  gateway/reverse_proxy_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7016 Merging to release-5.3: [TT-12442] necessary changes for new licensing logic (#6984)
  gateway/api_definition.go
  gateway/policy.go
  gateway/server.go
  gateway/testutil.go
Labels: Review effort 2/5

#7017 Merging to release-5.3: [TT-12442] changes required in gateway for new licensing to work (#6985)
  gateway/api_definition.go
  gateway/dashboard_register.go
  gateway/policy.go
Labels: Review effort 2/5

#7018 Merging to release-5.3: [TT-12442] Force gw reload after registration to have synced polciies and apis (#6988)
  gateway/dashboard_register.go
  gateway/reverse_proxy_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7021 [TT-14435]: add mqtt test cases
  ee/middleware/streams/stream.go
  gateway/mw_streaming_amqp_test.go
  gateway/mw_streaming_mqtt_test.go
  go.mod
Labels: Tyk Product Development, Sub-task, Review effort 4/5

#7020 [TT-14365]Test/apply policies restricted types fix
  internal/policy/apply.go
  internal/policy/apply_test.go
Labels: bug, Tyk Product Development, Review effort 2/5

#7023 Merging to release-5.8: [TT-14365]Test/apply policies restricted types fix (#7020)
  internal/policy/apply.go
  internal/policy/apply_test.go
Labels: Review effort 2/5

#7019 [TT-14596] Investigate flaky amqp integration tests
  gateway/mw_streaming_amqp_test.go
Labels: Tyk Product Development, Task, Review effort 3/5

#7026 [TT-14446] Add an integration test for Input (http_server) → Output(amqp_1) scenario
  gateway/mw_streaming_amqp_test.go
Labels: Tyk Product Development, Task, Review effort 3/5

#7024 TT-14590 kinopenapi CVE fix - Use internal fork of kinopen-api and import update gql translator
  apidef/adapter/openapi.go
  apidef/oas/authentication.go
  apidef/oas/default.go
  apidef/oas/default_test.go
  apidef/oas/example.go
  apidef/oas/example_test.go
  apidef/oas/fixtures_test.go
  apidef/oas/oas.go
  apidef/oas/oas_test.go
  apidef/oas/old_oas.go
  apidef/oas/operation.go
  apidef/oas/operation_test.go
  apidef/oas/root_test.go
  apidef/oas/security.go
  apidef/oas/security_test.go
  apidef/oas/validator_test.go
  apidef/streams/validator_test.go
  ctx/ctx_test.go
  gateway/api.go
  gateway/api_definition.go
  gateway/api_definition_test.go
  gateway/api_test.go
  gateway/looping_test.go
  gateway/mock_response.go
  gateway/mock_response_test.go
  gateway/model_apispec.go
  gateway/mw_oas_validate_request.go
  gateway/mw_oas_validate_request_test.go
  gateway/mw_streaming_test.go
  gateway/mw_version_check.go
  gateway/testutil.go
  go.mod
  go.sum
  goplugin/mw_go_plugin_test.go
  internal/oasutil/paths.go
  internal/oasutil/paths_test.go
Labels: Tyk Product Development, Story, Review effort 2/5

#7029 Merging to release-5.8: TT-14590 kinopenapi CVE fix - Use internal fork of kinopen-api and import update gql translator (#7024)
  apidef/adapter/openapi.go
  apidef/oas/authentication.go
  apidef/oas/default.go
  apidef/oas/default_test.go
  apidef/oas/example.go
  apidef/oas/example_test.go
  apidef/oas/fixtures_test.go
  apidef/oas/oas.go
  apidef/oas/oas_test.go
  apidef/oas/old_oas.go
  apidef/oas/operation.go
  apidef/oas/operation_test.go
  apidef/oas/root_test.go
  apidef/oas/security.go
  apidef/oas/security_test.go
  apidef/oas/validator_test.go
  apidef/streams/validator_test.go
  ctx/ctx_test.go
  gateway/api.go
  gateway/api_definition.go
  gateway/api_definition_test.go
  gateway/api_test.go
  gateway/looping_test.go
  gateway/mock_response.go
  gateway/mock_response_test.go
  gateway/model_apispec.go
  gateway/mw_oas_validate_request.go
  gateway/mw_oas_validate_request_test.go
  gateway/mw_streaming_test.go
  gateway/mw_version_check.go
  gateway/testutil.go
  go.mod
  go.sum
  goplugin/mw_go_plugin_test.go
  internal/oasutil/paths.go
  internal/oasutil/paths_test.go
Labels: Tyk Product Development, Story, Review effort 2/5

#7028 fix CVE for release-5.3
  apidef/adapter/openapi.go
  apidef/oas/authentication.go
  apidef/oas/default.go
  apidef/oas/default_test.go
  apidef/oas/example.go
  apidef/oas/example_test.go
  apidef/oas/oas.go
  apidef/oas/oas_test.go
  apidef/oas/old_oas.go
  apidef/oas/operation.go
  apidef/oas/operation_test.go
  apidef/oas/root_test.go
  apidef/oas/security.go
  apidef/oas/security_test.go
  apidef/oas/validator_test.go
  gateway/api.go
  gateway/api_definition.go
  gateway/api_test.go
  gateway/looping_test.go
  gateway/mock_response.go
  gateway/mock_response_test.go
  gateway/mw_oas_validate_request.go
  gateway/mw_oas_validate_request_test.go
  gateway/mw_version_check.go
  gateway/testutil.go
  go.mod
  go.sum
  goplugin/mw_go_plugin_test.go
  internal/oasutil/paths.go
  internal/oasutil/paths_test.go
Labels: Review effort 2/5

#7035 [TT-14738] Crypto and jwt dependencies upgrade to CVE fix
  go.mod
  go.sum
Labels: Review effort 2/5

#7037 Merging to release-5.3.11: [TT-14738] Crypto and jwt dependencies upgrade to CVE fix (#7035)
  go.mod
  go.sum
Labels: Review effort 2/5
