Repository TykTechnologies/tyk, pull requests merged in 2025-10, with the labels that each got.

#7397 Merging to release-5.8: [TT-15863] fix random version picking for not versioned API (#7380)
  gateway/api_definition.go
  gateway/api_definition_test.go
Labels: bug, Tyk Product Development

#7395 [TT-15860] initial fix for tls log
  ee/middleware/upstreamoauth/oauth_client_utils.go
  ee/middleware/upstreamoauth/oauth_client_utils_test.go
  ee/middleware/upstreamoauth/provider_client_credentials.go
  ee/middleware/upstreamoauth/provider_password_authentication.go
  gateway/event_handler_webhooks.go
  gateway/host_checker.go
  gateway/service_discovery.go
  internal/httpclient/factory.go
  internal/httpclient/factory_mtls_security_test.go
Labels: bug, Tyk Product Development, Review effort 3/5

#7403 [Regression]Mock response requests produce a warning level message "session not found. sending inappropriate rate-limit headers"
  gateway/model_apispec.go
Labels: bug, Tyk Product Development, Review effort 1/5

#7413 [TT-15904] revert golangcilint return exit code 0 to run ci tests on push to master
  .github/workflows/ci-tests.yml
Labels: Tyk Product Development, Story, Review effort 2/5

#7411 [TT-15901] Enhance AuthORWrapper to support authentication methods without SecuritySchemes
  apidef/oas/security.go
  apidef/oas/security_test.go
  gateway/api_loader.go
  gateway/mw_auth_or_wrapper.go
  gateway/mw_auth_or_wrapper_test.go
Labels: bug, Tyk Product Development, Review effort 4/5
